(()=>{
 const ROUTES_KEY="porudzbine-routes-v1";
 const list=document.getElementById("customerSettingsList"),search=document.getElementById("customerSettingsSearch"),count=document.getElementById("customerCount");
 if(!list)return;
 const norm=v=>String(v||"").trim().toLocaleLowerCase("sr");
 const fmt=v=>v?new Intl.DateTimeFormat("sr-RS",{dateStyle:"short"}).format(new Date(v)):"Nema";
 function allNames(){return [...new Set([...Object.keys(state.customers||{}),...(state.orders||[]).map(o=>o.customer)])].filter(Boolean);}
 function stats(name){const orders=customerOrders(name);return{last:orders[0]?.createdAt||null,total:orders.reduce((s,o)=>s+Object.values(o.items||{}).reduce((a,n)=>a+(Number(n)||0),0),0)};}
 function meta(name){return state.customers[name]||{};}
 function save(){persist();renderCustomerList();renderHistory();window.dispatchEvent(new Event("customers-changed"));}
 function updateRoutes(oldName,newName){try{const routes=JSON.parse(localStorage.getItem(ROUTES_KEY)||"{}");Object.keys(routes).forEach(day=>{const updated=(routes[day]||[]).map(n=>norm(n)===norm(oldName)?newName:n).map(n=>String(n||"").trim()).filter(Boolean);routes[day]=updated.filter((name,index,all)=>all.findIndex(other=>norm(other)===norm(name))===index);});localStorage.setItem(ROUTES_KEY,JSON.stringify(routes));}catch{}}
 function rename(oldName){const next=prompt(`Novi naziv za „${oldName}“:`,oldName)?.trim();if(!next||next===oldName)return;if(allNames().some(n=>norm(n)===norm(next)&&norm(n)!==norm(oldName))){showToast("Kupac sa tim nazivom već postoji. Koristi Spajanje.");return;}const oldMeta=meta(oldName);delete state.customers[oldName];state.customers[next]={...oldMeta};state.orders=state.orders.map(o=>norm(o.customer)===norm(oldName)?{...o,customer:next}:o);updateRoutes(oldName,next);if(norm(selectedCustomer)===norm(oldName)){selectedCustomer=next;els.customerInput.value=next;}save();render();showToast("Kupac je preimenovan svuda");}
 function edit(name){const m=meta(name);const code=prompt(`Šifra kupca „${name}“:`,m.code||"");if(code===null)return;const note=prompt(`Napomena za „${name}“:`,m.note||"");if(note===null)return;const duplicate=allNames().find(n=>n!==name&&code.trim()&&norm(meta(n).code)===norm(code));if(duplicate){showToast(`Šifru već koristi ${duplicate}`);return;}state.customers[name]={...m,code:code.trim(),note:note.trim()};if(norm(selectedCustomer)===norm(name))els.customerNote.value=note.trim();save();render();showToast("Podaci kupca su sačuvani");}
 function toggleFavorite(name){state.customers[name]={...meta(name),favorite:!meta(name).favorite};save();render();}
 function merge(source){const choices=allNames().filter(n=>norm(n)!==norm(source));if(!choices.length){showToast("Nema drugog kupca za spajanje");return;}const target=prompt(`U koji postojeći naziv da se spoji „${source}“?\n\nUpiši tačan naziv kupca:`)?.trim();if(!target)return;const exact=choices.find(n=>norm(n)===norm(target));if(!exact){showToast("Kupac sa tim nazivom nije pronađen");return;}if(!confirm(`Spojiti „${source}“ u „${exact}“? Sve porudžbine će pripasti kupcu „${exact}“.`))return;const sourceMeta=meta(source),targetMeta=meta(exact);state.customers[exact]={...sourceMeta,...targetMeta,note:targetMeta.note||sourceMeta.note||"",code:targetMeta.code||sourceMeta.code||"",favorite:Boolean(targetMeta.favorite||sourceMeta.favorite)};delete state.customers[source];state.orders=state.orders.map(o=>norm(o.customer)===norm(source)?{...o,customer:exact}:o);updateRoutes(source,exact);if(norm(selectedCustomer)===norm(source)){selectedCustomer=exact;els.customerInput.value=exact;}save();render();showToast("Kupci su spojeni");}
 function remove(name){const withOrders=confirm(`Obrisati i sve stare porudžbine kupca „${name}“?\n\nOK = kupac i porudžbine\nOtkaži = sledeći izbor`);if(withOrders){if(!confirm("Ovo trajno briše sve porudžbine tog kupca. Nastaviti?"))return;state.orders=state.orders.filter(o=>norm(o.customer)!==norm(name));delete state.customers[name];updateRoutes(name,"");save();render();showToast("Kupac i porudžbine su obrisani");return;}if(!confirm(`Obrisati samo kupca „${name}“ sa liste? Stare porudžbine ostaju.`))return;delete state.customers[name];updateRoutes(name,"");save();render();showToast("Kupac je uklonjen iz svih tura, istorija je sačuvana");}
 function render(){const q=norm(search.value);const names=allNames().filter(name=>!q||norm(name).includes(q)||norm(meta(name).code).includes(q)).sort((a,b)=>Number(Boolean(meta(b).favorite))-Number(Boolean(meta(a).favorite))||a.localeCompare(b,"sr"));count.textContent=`${names.length} kupaca`;list.innerHTML="";if(!names.length){list.innerHTML='<div class="empty-state">Nema pronađenih kupaca.</div>';return;}names.forEach(name=>{const s=stats(name),m=meta(name),card=document.createElement("article");card.className="customer-setting-card";card.innerHTML=`<div class="customer-setting-head"><div><strong>${m.favorite?"⭐ ":""}${escapeHtml(name)}</strong><div class="customer-code">Šifra: ${escapeHtml(m.code||"—")}</div></div><button type="button" class="favorite-button" aria-label="Omiljeni">${m.favorite?"★":"☆"}</button></div><div class="customer-setting-stats"><span>Poslednja: <strong>${fmt(s.last)}</strong></span><span>Ukupno: <strong>${s.total}</strong></span></div>${m.note?`<div class="customer-setting-note">${escapeHtml(m.note)}</div>`:""}<div class="customer-setting-actions"><button type="button" data-a="edit">Šifra i napomena</button><button type="button" data-a="rename">Preimenuj</button><button type="button" data-a="merge">Spoji</button><button type="button" data-a="delete" class="danger">Obriši</button></div>`;card.querySelector(".favorite-button").onclick=()=>toggleFavorite(name);card.querySelector('[data-a="edit"]').onclick=()=>edit(name);card.querySelector('[data-a="rename"]').onclick=()=>rename(name);card.querySelector('[data-a="merge"]').onclick=()=>merge(name);card.querySelector('[data-a="delete"]').onclick=()=>remove(name);list.appendChild(card);});}
 search.addEventListener("input",render);document.getElementById("settingsBtn")?.addEventListener("click",render);window.addEventListener("customers-changed",render);document.getElementById("saveBtn")?.addEventListener("click",()=>setTimeout(render,0));render();
})();