(()=>{
 const $=id=>document.getElementById(id),list=$("customerModuleList"),detail=$("customerDetailContent"),form=$("customerForm");
 if(!list)return;
 const norm=v=>String(v||"").trim().toLocaleLowerCase("sr"),fmt=v=>v&&!Number.isNaN(+new Date(v))?new Intl.DateTimeFormat("sr-RS",{dateStyle:"medium"}).format(new Date(v)):"Nema";
 const names=()=>[...new Set([...Object.keys(state.customers||{}),...(state.orders||[]).map(o=>o.customer)])].filter(Boolean).sort((a,b)=>a.localeCompare(b,"sr"));
 const keyFor=name=>Object.keys(state.customers||{}).find(k=>norm(k)===norm(name))||name,metaFor=name=>state.customers[keyFor(name)]||{},phone=meta=>meta.mobile||meta.phone||"";
 function navigation(meta){const target=String(meta.gps||"").trim()||[meta.address,meta.city].filter(Boolean).join(", ");return target?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(target)}`:""}
 function show(view){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(view).classList.add("active");document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",view==="customersView"&&t.dataset.tab==="customers"));$("saveBar").classList.add("hidden");window.scrollTo({top:0})}
 function render(){const customers=names();list.innerHTML=customers.length?customers.map(name=>`<button class="customer-module-card-v266" type="button" role="listitem" data-customer="${escapeHtml(name)}"><span>${escapeHtml(name)}</span><b aria-hidden="true">›</b></button>`).join(""):'<div class="empty-state">Nema kupaca.</div>'}
 function openForm(name=""){const meta=name?metaFor(name):{};$("customerFormTitle").textContent=name?"Izmeni kupca":"Novi kupac";$("customerOriginalName").value=name;for(const el of form.elements)if(el.name)el.value=meta[el.name]??(el.name==="name"?name:el.name==="status"?"active":el.name==="priority"?"1":"");show("customerFormView")}
 function orderValue(order){if(order.value!=null)return Number(order.value);if(order.total!=null)return Number(order.total);return 0}
 function sectionContent(name,section){const m=metaFor(name),history=customerOrders(name),notes=Array.isArray(m.notes)?m.notes:[];
  if(section==="history")return history.length?history.map(o=>`<article class="customer-history-row-v266"><strong>${fmt(o.createdAt)}</strong><span>Vrednost: ${orderValue(o).toLocaleString("sr-RS")} RSD</span></article>`).join(""):'<div class="empty-state">Nema prethodnih porudžbina.</div>';
  if(section==="notes")return `<form id="customerNoteForm" class="note-form-v266"><textarea required placeholder="Unesite napomenu"></textarea><button class="primary" type="submit">Dodaj napomenu</button></form>${notes.slice().reverse().map(n=>`<article class="customer-note-item-v266"><time>${fmt(n.createdAt)}</time><p>${escapeHtml(n.text)}</p></article>`).join("")||'<div class="empty-state">Nema napomena.</div>'}`;
  return `<div class="customer-info-grid-v266">${[["Ime",name],["Naziv firme",m.company],["PIB",m.pib],["Matični broj",m.registrationNumber],["Telefon",phone(m)],["Email",m.email],["Adresa",[m.address,m.city].filter(Boolean).join(", ")],["Kontakt osoba",m.contactPerson],["Radno vreme",m.workingHours],["Status",m.status==="inactive"?"Neaktivan":"Aktivan"]].map(([label,value])=>`<div><span>${label}</span><strong>${escapeHtml(value||"—")}</strong></div>`).join("")}</div>`;
 }
 function renderDetail(name,section="basic"){const m=metaFor(name),tel=phone(m),nav=navigation(m);detail.innerHTML=`<section class="customer-detail-v266"><div class="customer-detail-sticky-v266"><button id="backCustomersBtn" class="text-button" type="button">‹ Svi kupci</button><h2>${escapeHtml(name)}</h2></div><nav class="customer-detail-tabs-v266" aria-label="Opcije kupca"><button class="${section==="basic"?"active":""}" data-section="basic">Osnovni podaci</button><button data-action="order">Nova porudžbina</button><button class="${section==="history"?"active":""}" data-section="history">Istorija porudžbina</button><button class="${section==="notes"?"active":""}" data-section="notes">Napomene</button>${tel?`<a href="tel:${escapeHtml(tel)}">Pozovi</a>`:'<button disabled>Pozovi</button>'}${nav?`<a href="${nav}" target="_blank" rel="noopener">Navigacija</a>`:'<button disabled>Navigacija</button>'}<button data-action="edit">Izmeni kupca</button><button data-action="delete" class="danger">Obriši kupca</button></nav><section class="card customer-detail-panel-v266">${sectionContent(name,section)}</section></section>`;
  $("backCustomersBtn").onclick=()=>{show("customersView");render()};detail.querySelectorAll("[data-section]").forEach(button=>button.onclick=()=>renderDetail(name,button.dataset.section));detail.querySelector('[data-action="order"]').onclick=()=>{els.customerInput.value=name;selectCustomer(name);switchTab("order")};detail.querySelector('[data-action="edit"]').onclick=()=>openForm(name);detail.querySelector('[data-action="delete"]').onclick=()=>remove(name);
  $("customerNoteForm")?.addEventListener("submit",event=>{event.preventDefault();const text=event.currentTarget.querySelector("textarea").value.trim();if(!text)return;m.notes=[...(Array.isArray(m.notes)?m.notes:[]),{id:makeId(),createdAt:new Date().toISOString(),text}];state.customers[keyFor(name)]=m;saveAndRender("Napomena je dodata");renderDetail(name,"notes")});show("customerDetailView")
 }
 function saveAndRender(message){persist();renderCustomerList();window.dispatchEvent(new Event("customers-changed"));render();if(message)showToast(message)}
 function remove(name){if(!confirm(`Obrisati kupca „${name}“? Istorija porudžbina ostaje sačuvana.`))return;delete state.customers[keyFor(name)];const routeKey="porudzbine-routes-v1",routes=JSON.parse(localStorage.getItem(routeKey)||"{}");Object.keys(routes).forEach(day=>routes[day]=(routes[day]||[]).filter(customer=>norm(customer)!==norm(name)));localStorage.setItem(routeKey,JSON.stringify(routes));saveAndRender("Kupac je obrisan");show("customersView")}
 form.addEventListener("submit",event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form)),original=$("customerOriginalName").value,name=data.name.trim();if(!name)return;if(names().some(n=>norm(n)===norm(name)&&norm(n)!==norm(original))){showToast("Kupac sa tim imenom već postoji");return}const old=original?metaFor(original):{};delete data.name;state.customers[name]={...old,...data,priority:Number(data.priority)};if(original&&norm(original)!==norm(name)){delete state.customers[keyFor(original)];state.orders=state.orders.map(o=>norm(o.customer)===norm(original)?{...o,customer:name}:o)}saveAndRender(original?"Kupac je izmenjen":"Kupac je dodat");renderDetail(name)});
 list.addEventListener("click",event=>{const card=event.target.closest("[data-customer]");if(card)renderDetail(card.dataset.customer)});$("cancelCustomerForm").onclick=()=>{show("customersView");render()};document.querySelector('.tab[data-tab="customers"]').addEventListener("click",()=>{show("customersView");render()});window.addEventListener("customers-changed",render);render();
})();
