(()=>{
 const view=document.getElementById("customersView"),list=document.getElementById("customerModuleList"),search=document.getElementById("customerModuleSearch"),filter=document.getElementById("customerModuleFilter"),sort=document.getElementById("customerModuleSort");if(!view)return;
 const SORT_KEY="porudzbine-customer-sort-v265",DAY_MS=86400000;sort.value=localStorage.getItem(SORT_KEY)||"name";
 const norm=value=>String(value||"").trim().toLocaleLowerCase("sr"),names=()=>[...new Set([...Object.keys(state.customers||{}),...(state.orders||[]).map(order=>order.customer)])].filter(Boolean);
 const customerKey=name=>Object.keys(state.customers||{}).find(key=>norm(key)===norm(name))||name;
 const orders=name=>customerOrders(name),format=value=>value?new Intl.DateTimeFormat("sr-RS",{dateStyle:"medium"}).format(new Date(value)):"Nema";
 function commit(){persist();renderCustomerList();window.dispatchEvent(new Event("customers-changed"));render();}
 function fields(name=""){const meta=state.customers[customerKey(name)]||{};return{name:prompt("Naziv kupca:",name),phone:null,address:null,note:null,meta};}
 function add(){const data=fields();if(data.name===null)return;const name=data.name.trim();if(!name){showToast("Naziv kupca je obavezan");return;}if(names().some(item=>norm(item)===norm(name))){showToast("Kupac već postoji");return;}const phone=prompt("Telefon kupca:","");if(phone===null)return;const address=prompt("Adresa kupca:","");if(address===null)return;const note=prompt("Napomena:","");if(note===null)return;state.customers[name]={phone:phone.trim(),address:address.trim(),note:note.trim()};commit();showToast("Kupac je dodat");}
 function edit(name){const key=customerKey(name),meta=state.customers[key]||{},next=prompt("Naziv kupca:",name);if(next===null||!next.trim())return;const newName=next.trim();if(names().some(item=>norm(item)===norm(newName)&&norm(item)!==norm(name))){showToast("Kupac sa tim nazivom već postoji");return;}const phone=prompt("Telefon kupca:",meta.phone||"");if(phone===null)return;const address=prompt("Adresa kupca:",meta.address||"");if(address===null)return;const note=prompt("Napomena:",meta.note||"");if(note===null)return;const lastVisitDate=prompt("Poslednja poseta (GGGG-MM-DD, opciono):",meta.lastVisitDate?.slice(0,10)||"");if(lastVisitDate===null)return;if(lastVisitDate&&!/^\d{4}-\d{2}-\d{2}$/.test(lastVisitDate)){showToast("Datum mora biti u obliku GGGG-MM-DD");return;}delete state.customers[key];state.customers[newName]={...meta,phone:phone.trim(),address:address.trim(),note:note.trim(),lastVisitDate:lastVisitDate?`${lastVisitDate}T12:00:00`:""};if(newName!==name){state.orders=state.orders.map(order=>norm(order.customer)===norm(name)?{...order,customer:newName}:order);const routes=JSON.parse(localStorage.getItem("porudzbine-routes-v1")||"{}");Object.keys(routes).forEach(day=>routes[day]=(routes[day]||[]).map(item=>norm(item)===norm(name)?newName:item));localStorage.setItem("porudzbine-routes-v1",JSON.stringify(routes));}commit();showToast("Kupac je izmenjen");}
 function remove(name){if(!confirm(`Obrisati kupca „${name}“? Istorija porudžbina ostaje sačuvana.`))return;delete state.customers[customerKey(name)];const routes=JSON.parse(localStorage.getItem("porudzbine-routes-v1")||"{}");Object.keys(routes).forEach(day=>routes[day]=(routes[day]||[]).filter(item=>norm(item)!==norm(name)));localStorage.setItem("porudzbine-routes-v1",JSON.stringify(routes));commit();showToast("Kupac je obrisan");}
 function navigation(address){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;}
 function render(){const query=norm(search.value),kind=filter.value,today=new Date(),route=(JSON.parse(localStorage.getItem("porudzbine-routes-v1")||"{}")[String(today.getDay())]||[]),routeIndex=new Map(route.map((name,index)=>[norm(name),index])),records=names().map(name=>{const meta=state.customers[customerKey(name)]||{},history=orders(name),last=history[0],lastDate=new Date(meta.lastVisitDate||last?.createdAt||0),waiting=lastDate.getTime()?Math.max(0,Math.floor((today-lastDate)/DAY_MS)):Number.MAX_SAFE_INTEGER;return{name,meta,waiting,route:routeIndex.get(norm(name))??Number.MAX_SAFE_INTEGER};});const visible=records.filter(({name,meta})=>{const haystack=norm([name,meta.address,meta.place,meta.city,meta.phone].join(" "));return(!query||haystack.includes(query))&&(kind==="all"||kind==="favorites"&&meta.favorite||kind==="scheduled"&&meta.visitMode==="scheduled"||kind==="manual"&&meta.visitMode==="manual");}).sort((a,b)=>sort.value==="priority"?Number(Boolean(b.meta.favorite))-Number(Boolean(a.meta.favorite))||a.name.localeCompare(b.name,"sr"):sort.value==="waiting"?b.waiting-a.waiting||a.name.localeCompare(b.name,"sr"):sort.value==="route"?a.route-b.route||a.name.localeCompare(b.name,"sr"):a.name.localeCompare(b.name,"sr")).map(item=>item.name);const fragment=document.createDocumentFragment();visible.forEach(name=>{const meta=state.customers[customerKey(name)]||{},history=orders(name),last=history[0],card=document.createElement("article");card.className="customer-module-card-v266";card.innerHTML=`<div class="customer-module-head-v266"><div><h3>${meta.favorite?"⭐ ":""}${escapeHtml(name)}</h3>${meta.phone?`<a href="tel:${escapeHtml(meta.phone)}">${escapeHtml(meta.phone)}</a>`:"<span>Telefon nije unet</span>"}</div><div><button data-action="edit" type="button">Izmeni</button><button data-action="delete" class="danger" type="button">Obriši</button></div></div>${meta.address?`<p class="customer-address-v266">📍 ${escapeHtml(meta.address)}</p>`:""}${meta.note?`<p class="customer-note-v266">${escapeHtml(meta.note)}</p>`:""}<div class="customer-dates-v266"><span>Poslednja porudžbina <strong>${format(last?.createdAt)}</strong></span><span>Poslednja poseta <strong>${format(meta.lastVisitDate||last?.createdAt)}</strong></span></div><div class="customer-quick-v266">${meta.phone?`<a class="primary" href="tel:${escapeHtml(meta.phone)}">Pozovi</a>`:""}${meta.address?`<a class="secondary" href="${navigation(meta.address)}" target="_blank" rel="noopener">Navigacija</a>`:""}</div>`;card.querySelector('[data-action="edit"]').onclick=()=>edit(name);card.querySelector('[data-action="delete"]').onclick=()=>remove(name);fragment.appendChild(card);});list.replaceChildren(fragment);if(!visible.length)list.innerHTML='<div class="empty-state">Nema pronađenih kupaca.</div>';}
 function activate(){document.querySelectorAll(".view").forEach(item=>item.classList.remove("active"));view.classList.add("active");document.getElementById("saveBar").classList.add("hidden");render();}
 document.querySelector('.tab[data-tab="customers"]').addEventListener("click",activate);document.querySelectorAll('.tab:not([data-tab="customers"])').forEach(tab=>tab.addEventListener("click",()=>view.classList.remove("active")));document.getElementById("addCustomerModuleBtn").onclick=add;search.addEventListener("input",render);filter.addEventListener("change",render);sort.addEventListener("change",()=>{localStorage.setItem(SORT_KEY,sort.value);render();});window.addEventListener("customers-changed",render);render();
})();
