(()=>{
 const ROUTES_KEY="porudzbine-routes-v1",STATUS_KEY="porudzbine-route-status-v1",CARRY_KEY="porudzbine-route-carry-v263",DAY_MS=86400000;
 const $=id=>document.getElementById(id),norm=value=>String(value||"").trim().toLocaleLowerCase("sr");
 const load=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}};
 const dateKey=(value=new Date())=>{const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;};
 const unique=names=>{const seen=new Set();return names.filter(name=>{const key=norm(name);if(!key||seen.has(key))return false;seen.add(key);return true;});};
 function customerMeta(name){const key=Object.keys(state.customers||{}).find(item=>norm(item)===norm(name));return key?state.customers[key]:{};}
 function weekStart(value){const date=new Date(value);date.setHours(12,0,0,0);date.setDate(date.getDate()-(date.getDay()===0?6:date.getDay()-1));return date;}
 function dueToday(name){const meta=customerMeta(name),today=new Date(),day=today.getDay();if(meta.visitMode==="manual"||meta.visitInterval==="manual")return false;if(meta.visitMode!=="scheduled"||meta.visitDay===undefined||meta.visitDay===null||!meta.visitInterval)return true;if(Number(meta.visitDay)!==day)return false;const interval=Number(meta.visitInterval);if(![14,21,28].includes(interval))return true;const start=new Date(`${meta.cycleStart||dateKey()}T12:00:00`),weeks=Math.round((weekStart(today)-weekStart(start))/(7*DAY_MS));return !Number.isNaN(start.getTime())&&weeks>=0&&weeks%(interval/7)===0;}
 function data(){
  const today=dateKey(),regular=(load(ROUTES_KEY,{})[String(new Date().getDay())]||[]).filter(dueToday),status=load(STATUS_KEY,{})[today]||{},orders=(state.orders||[]).filter(order=>dateKey(order.createdAt)===today),ordered=new Set(orders.map(order=>norm(order.customer)));
  const overdue=Object.values(load(CARRY_KEY,{})).map(item=>({...item,daysLate:Math.max(1,Math.round((new Date(`${today}T12:00:00`)-new Date(`${item.since}T12:00:00`))/DAY_MS))})).sort((a,b)=>b.daysLate-a.daysLate||a.customer.localeCompare(b.customer,"sr"));
  const list=unique([...overdue.map(item=>item.customer),...regular]),overdueMap=new Map(overdue.map(item=>[norm(item.customer),item]));
  const customers=list.map(name=>{const manual=status[norm(name)]?.status;return {name,overdue:overdueMap.get(norm(name))||null,type:manual==="completed"||ordered.has(norm(name))?"completed":manual==="not-today"?"not-today":"waiting"};});
  return {regular,overdue,customers};
 }
 function openCustomer(name){$("customerInput").value=name;selectCustomer(name);switchTab("order");window.scrollTo({top:0,behavior:"smooth"});}
 function render(){
  const host=$("dashboardContent");if(!host)return;const {overdue,customers}=data(),completed=customers.filter(item=>item.type==="completed").length,remaining=customers.filter(item=>item.type==="waiting").length,total=customers.length,percent=total?Math.round(completed/total*100):0,maxLate=overdue.reduce((max,item)=>Math.max(max,item.daysLate),0),urgent=overdue.filter(item=>item.daysLate===maxLate&&item.daysLate>0&&customers.find(customer=>norm(customer.name)===norm(item.customer))?.type==="waiting").length;
  const signature=JSON.stringify([dateKey(),total,completed,remaining,percent,Object.keys(state.customers||{}).length,overdue.map(item=>[item.customer,item.daysLate]),customers.map(item=>[item.name,item.type])]);if(host.dataset.dashboardSignature===signature)return;host.dataset.dashboardSignature=signature;
  const groups=[{label:"1 dan",test:days=>days===1,tone:"day-one"},{label:"2 dana",test:days=>days===2,tone:"day-two"},{label:"3 dana",test:days=>days===3,tone:"day-three"},{label:"4 dana",test:days=>days===4,tone:"day-three"},{label:"5+",test:days=>days>=5,tone:"day-three"}];
  host.innerHTML=`<section class="dashboard-heading"><div><p class="dashboard-eyebrow">Pregled pre polaska</p><h2 id="dashboardTitle">Dashboard</h2></div><span>${new Intl.DateTimeFormat("sr-RS",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</span></section><section class="dashboard-cards" aria-label="Najvažniji podaci"><article><span>Današnji kupci</span><strong>${total}</strong></article><article class="complete"><span>Završeni</span><strong>${completed}</strong></article><article class="late"><span>Zaostali</span><strong>${overdue.length}</strong></article><article class="urgent"><span>Hitni</span><strong>${urgent}</strong><small>čekaju najduže</small></article></section><section class="card dashboard-progress"><div class="section-title"><div><h3>Napredak rute</h3><p class="muted">Automatski se ažurira</p></div><strong>${percent}%</strong></div><div class="progress-track" role="progressbar" aria-label="Završena ruta" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent}"><span style="width:${percent}%"></span></div><div class="dashboard-stats"><span>Ukupno kupaca<strong>${Object.keys(state.customers||{}).length}</strong></span><span>Današnja ruta<strong>${total}</strong></span><span>Preostalo<strong>${remaining}</strong></span><span>Završeno<strong>${completed}</strong></span><span>Procenat završene rute<strong>${percent}%</strong></span></div></section><section id="dashboardOverdue" class="card dashboard-overdue"><div class="section-title"><div><h3>Zaostali kupci</h3><p class="muted">Grupisani prema broju dana čekanja</p></div><strong>${overdue.length}</strong></div><div class="overdue-accordions">${groups.map(group=>{const items=overdue.filter(item=>group.test(item.daysLate));return `<details class="${group.tone}" ${items.length?"open":""}><summary><span>${group.label}</span><strong>${items.length}</strong></summary><div>${items.length?items.map(item=>`<button type="button" data-customer="${escapeHtml(item.customer)}"><span>${escapeHtml(item.customer)}</span><small>Kasni ${item.daysLate} ${item.daysLate===1?"dan":"dana"}</small></button>`).join(""):'<p class="muted">Nema kupaca u ovoj grupi.</p>'}</div></details>`;}).join("")}</div></section>`;
  host.querySelectorAll("[data-customer]").forEach(button=>button.onclick=()=>openCustomer(button.dataset.customer));
 }
 function showFinished({customers=[]}={}){const waiting=customers.filter(item=>item.status?.type==="waiting"),late=waiting.filter(item=>item.overdue),maxLate=late.reduce((max,item)=>Math.max(max,item.overdue.daysLate),0),urgent=late.filter(item=>item.overdue.daysLate===maxLate).length,twoDays=late.filter(item=>item.overdue.daysLate===2).length,newLate=waiting.filter(item=>!item.overdue).length;$("finishRemaining").textContent=`${waiting.length} kupaca`;$("finishBreakdown").innerHTML=`<span><strong>${urgent}</strong> hitna</span><span><strong>${twoDays}</strong> starih dva dana</span><span><strong>${newLate}</strong> nova zaostala</span>`;$("routeFinishedDialog").showModal();}
 $("finishCloseBtn").onclick=()=>$("routeFinishedDialog").close();$("finishOverdueBtn").onclick=()=>{$("routeFinishedDialog").close();switchTab("dashboard");render();requestAnimationFrame(()=>$("dashboardOverdue")?.scrollIntoView({behavior:"smooth"}));};
 let renderFrame=0;const scheduleRender=()=>{if(renderFrame)return;renderFrame=requestAnimationFrame(()=>{renderFrame=0;render();});};
 document.querySelector('.tab[data-tab="dashboard"]')?.addEventListener("click",scheduleRender);window.addEventListener("order-saved",scheduleRender);window.addEventListener("routes-changed",scheduleRender);window.addEventListener("customers-changed",scheduleRender);window.addEventListener("storage",scheduleRender);window.showRouteFinishedDialog=showFinished;window.renderDashboard=scheduleRender;setTimeout(scheduleRender,0);
})();
