(()=>{"use strict";
const KEY="porudzbine-price-lists-v2",OLD_KEY="porudzbine-price-lists-v1",HKEY="porudzbine-price-history-v2",OLD_HKEY="porudzbine-price-history-v1";
const $=id=>document.getElementById(id),home=$("priceListsHome"),detail=$("priceListDetail"),root=$("priceLists"),input=$("priceImportInput");
let current=null,showArchived=false;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=v=>(window.escapeHtml?escapeHtml(String(v??"")):String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])));
const fmt=v=>new Intl.NumberFormat("sr-RS",{style:"currency",currency:"RSD"}).format(Number(v)||0),stamp=()=>new Date().toISOString(),uid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random();
function migrate(){if(!localStorage.getItem(KEY)){const old=read(OLD_KEY,[]).map(x=>({...x,description:x.description||"",createdAt:x.createdAt||x.updatedAt||stamp(),status:x.status||"active"}));save(KEY,old)}if(!localStorage.getItem(HKEY))save(HKEY,read(OLD_HKEY,[]))}
function lists(){return read(KEY,[])}function setLists(v){save(KEY,v)}function historyRows(){return read(HKEY,[])}function setHistory(v){save(HKEY,v)}
function products(){return (window.state?.products||[]).map(name=>({name,unit:"kom",price:0,updatedAt:stamp()}))}
function toast(msg){window.showToast?showToast(msg):alert(msg)}
function render(){home.classList.remove("hidden");detail.classList.add("hidden");current=null;const all=lists().filter(x=>showArchived?x.status==="archived":x.status!=="archived");root.innerHTML=`<div class="price-home-tools"><button id="comparePriceLists" type="button">Poređenje cenovnika</button><button id="toggleArchivedPriceLists" type="button">${showArchived?"Prikaži aktivne":"Arhivirani cenovnici"}</button></div>`+(all.length?all.map(x=>`<article class="price-list-card"><div><strong>${esc(x.name)}</strong><span>${esc(x.description||"Bez opisa")}</span><small>${x.items.length} artikala · izmenjeno ${new Date(x.updatedAt).toLocaleDateString("sr-RS")}</small></div><div class="price-card-actions"><button data-open="${x.id}">Otvori</button>${x.status==="archived"?`<button data-restore-list="${x.id}">Vrati</button>`:`<button data-rename="${x.id}">Izmeni</button><button data-copy="${x.id}">Kopiraj</button><button data-archive="${x.id}">Arhiviraj</button>`}</div></article>`).join(""):`<div class="statistics-empty">${showArchived?"Nema arhiviranih cenovnika":"Još nema napravljenih cenovnika"}</div>`);
$("comparePriceLists").onclick=compareScreen;$("toggleArchivedPriceLists").onclick=()=>{showArchived=!showArchived;render()};root.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>open(b.dataset.open));root.querySelectorAll("[data-rename]").forEach(b=>b.onclick=()=>editMeta(b.dataset.rename));root.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>copy(b.dataset.copy));root.querySelectorAll("[data-archive]").forEach(b=>b.onclick=()=>archive(b.dataset.archive));root.querySelectorAll("[data-restore-list]").forEach(b=>b.onclick=()=>restoreList(b.dataset.restoreList))}
function mutate(fn,rerender=true){const all=lists(),x=all.find(v=>v.id===current);if(!x)return;fn(x);x.updatedAt=stamp();setLists(all);if(rerender)open(current)}
function editMeta(i){const all=lists(),x=all.find(v=>v.id===i);if(!x)return;const name=prompt("Naziv cenovnika",x.name)?.trim();if(!name)return;const description=prompt("Opis cenovnika",x.description||"")??x.description||"";x.name=name;x.description=description.trim();x.updatedAt=stamp();setLists(all);render()}
function copy(i){const all=lists(),x=all.find(v=>v.id===i);if(!x)return;const name=prompt("Naziv kopije",`Kopija - ${x.name}`)?.trim();if(!name)return;all.push({...structuredClone(x),id:uid(),name,createdAt:stamp(),updatedAt:stamp(),status:"active"});setLists(all);render()}
function archive(i){if(!confirm("Arhivirati ovaj cenovnik? Ostaće dostupan za pregled i izvoz."))return;const all=lists(),x=all.find(v=>v.id===i);if(x){x.status="archived";x.updatedAt=stamp();setLists(all);render()}}
function restoreList(i){const all=lists(),x=all.find(v=>v.id===i);if(x){x.status="active";x.updatedAt=stamp();setLists(all);showArchived=false;render()}}
function addHistory(list,item,oldPrice,newPrice){const h=historyRows();h.unshift({id:uid(),listId:list.id,listName:list.name,product:item.name,oldPrice:Number(oldPrice)||0,newPrice:Number(newPrice)||0,at:stamp()});setHistory(h)}
function change(itemName,price,rerender=true){let changed=false;mutate(x=>{const p=x.items.find(v=>v.name===itemName),value=Number(price);if(!p||!Number.isFinite(value)||value<0)return;if(Number(p.price)===value)return;addHistory(x,p,p.price,value);p.price=value;p.updatedAt=stamp();changed=true},rerender);return changed}
function historyDialog(item){const x=lists().find(v=>v.id===current),rows=historyRows().filter(h=>h.product===item&&h.listId===current);if(!rows.length)return alert("Nema istorije promena cena");const text=rows.slice(0,30).map((h,n)=>`${n+1}. ${new Date(h.at).toLocaleString("sr-RS")}: ${fmt(h.oldPrice)} → ${fmt(h.newPrice)}`).join("\n");if(confirm(`${text}\n\nVrati prethodnu cenu (${fmt(rows[0].oldPrice)})?`))change(item,rows[0].oldPrice)}
function roundTo(value,step){return Math.round(Number(value||0)/step)*step}
function group(){const x=lists().find(v=>v.id===current);if(!x)return;const mode=$("priceBulkMode").value,n=Number($("priceBulkValue").value),selected=[...detail.querySelectorAll("[data-select]:checked")].map(b=>b.dataset.select),items=x.items.filter(p=>!selected.length||selected.includes(p.name));if(!items.length)return toast("Izaberi artikle");let calc=p=>mode==="up"?p*(1+n/100):mode==="down"?p*(1-n/100):mode==="same"?n:mode==="round05"?roundTo(p,.5):mode==="round1"?roundTo(p,1):mode==="round5"?roundTo(p,5):roundTo(p,10);const old=items.reduce((s,p)=>s+Number(p.price||0),0),values=items.map(p=>Math.max(0,calc(Number(p.price||0)))),neu=values.reduce((s,p)=>s+p,0),pct=old?(neu/old-1)*100:0;if(!confirm(`Pregled promene\nArtikala: ${items.length}\nStara ukupna vrednost: ${fmt(old)}\nNova ukupna vrednost: ${fmt(neu)}\nPromena: ${pct.toFixed(2)}%\n\nPrimeni izmene?`))return;items.forEach((p,idx)=>change(p.name,values[idx],false));open(current)}
function exportFiles(pdf=false){const x=lists().find(v=>v.id===current);if(!x)return;const date=new Date().toISOString().slice(0,10),rows=[["Artikal","Jedinica mere","Cena"],...x.items.map(p=>[p.name,p.unit,p.price])];if(pdf)FileExport.pdf(x.name,`Datum generisanja: ${new Date().toLocaleDateString("sr-RS")}`,[{title:"Cenovnik",rows}]).then(b=>FileExport.share(b,`Cenovnik_${x.name.replace(/\W+/g,"_")}_${date}.pdf`));else FileExport.share(FileExport.xlsx({Cenovnik:rows}),`Cenovnik_${x.name.replace(/\W+/g,"_")}_${date}.xlsx`)}
function compareScreen(){const all=lists().filter(x=>x.status!=="archived");home.classList.add("hidden");detail.classList.remove("hidden");if(all.length<2){detail.innerHTML='<button id="pricesBack" class="statistics-overview">‹ Cenovnici</button><div class="statistics-empty">Potrebna su najmanje dva aktivna cenovnika za poređenje.</div>';$("pricesBack").onclick=render;return}const opts=all.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");detail.innerHTML=`<button id="pricesBack" class="statistics-overview">‹ Cenovnici</button><div class="settings-section"><h3>Poređenje cenovnika</h3><div class="price-compare-controls"><select id="compareLeft">${opts}</select><select id="compareRight">${opts}</select><label><input id="compareOnlyDiff" type="checkbox"> Samo artikli sa razlikom</label></div><div id="priceCompareTable"></div></div>`;$("pricesBack").onclick=render;$("compareRight").selectedIndex=1;[$("compareLeft"),$("compareRight"),$("compareOnlyDiff")].forEach(el=>el.onchange=renderComparison);renderComparison()}
function renderComparison(){const left=lists().find(x=>x.id===$("compareLeft").value),right=lists().find(x=>x.id===$("compareRight").value),only=$("compareOnlyDiff").checked;if(!left||!right)return;const names=[...new Set([...left.items.map(x=>x.name),...right.items.map(x=>x.name)])].sort((a,b)=>a.localeCompare(b,"sr")),rows=names.map(name=>{const a=left.items.find(x=>x.name===name)?.price??null,b=right.items.find(x=>x.name===name)?.price??null,d=(Number(b)||0)-(Number(a)||0),pct=Number(a)?d/Number(a)*100:null;return{name,a,b,d,pct}}).filter(r=>!only||r.a!==r.b);$("priceCompareTable").innerHTML=`<div class="price-compare-head"><b>Artikal</b><b>${esc(left.name)}</b><b>${esc(right.name)}</b><b>Razlika</b></div>${rows.map(r=>`<div class="price-compare-row ${r.d>0?"price-up":r.d<0?"price-down":"price-same"}"><span>${esc(r.name)}</span><span>${r.a==null?"—":fmt(r.a)}</span><span>${r.b==null?"—":fmt(r.b)}</span><span>${fmt(r.d)}${r.pct==null?"":` (${r.pct.toFixed(1)}%)`}</span></div>`).join("")||'<div class="statistics-empty">Nema razlika</div>'}`}
function open(i){current=i;const x=lists().find(v=>v.id===i);if(!x)return render();home.classList.add("hidden");detail.classList.remove("hidden");detail.innerHTML=`<button class="statistics-overview" id="pricesBack">‹ Svi cenovnici</button><div class="settings-section"><div class="section-title"><div><h3>${esc(x.name)}</h3><p class="muted">${esc(x.description||"")} · Poslednja izmena ${new Date(x.updatedAt).toLocaleString("sr-RS")}</p></div></div>${x.status==="archived"?'<div class="statistics-empty">Ovaj cenovnik je arhiviran. Dostupan je samo za pregled i izvoz.</div>':`<div class="price-tools"><select id="priceBulkMode"><option value="up">Povećaj za %</option><option value="down">Smanji za %</option><option value="same">Postavi istu cenu</option><option value="round05">Zaokruži na 50 para</option><option value="round1">Zaokruži na dinar</option><option value="round5">Zaokruži na 5 dinara</option><option value="round10">Zaokruži na 10 dinara</option></select><input id="priceBulkValue" type="number" value="5" min="0" step="0.01"><button id="applyPriceBulk" class="primary">Pregled i primena</button></div>`}<div class="price-export">${x.status!=="archived"?'<button id="priceImport">Uvoz CSV/Excel tabele</button>':''}<button id="priceXlsx">Izvoz u Excel</button><button id="pricePdf">Izvoz u PDF</button></div><div class="price-items">${x.items.map(p=>`<div>${x.status!=="archived"?`<input type="checkbox" data-select="${esc(p.name)}">`:""}<span><strong>${esc(p.name)}</strong><small>${esc(p.unit)} · ${new Date(p.updatedAt).toLocaleDateString("sr-RS")}</small></span><input data-price="${esc(p.name)}" type="number" min="0" step="0.01" value="${p.price}" ${x.status==="archived"?"disabled":""}><button data-history="${esc(p.name)}">Istorija</button></div>`).join("")}</div></div>`;$("pricesBack").onclick=render;$("applyPriceBulk")&&($("applyPriceBulk").onclick=group);$("priceXlsx").onclick=()=>exportFiles();$("pricePdf").onclick=()=>exportFiles(true);$("priceImport")&&($("priceImport").onclick=()=>input.click());detail.querySelectorAll("[data-price]").forEach(el=>el.onchange=()=>change(el.dataset.price,el.value));detail.querySelectorAll("[data-history]").forEach(el=>el.onclick=()=>historyDialog(el.dataset.history))}
$("newPriceListBtn")?.addEventListener("click",()=>{const name=prompt("Naziv novog cenovnika","Standardni")?.trim();if(!name)return;const description=prompt("Kratak opis cenovnika","")||"",all=lists();all.push({id:uid(),name,description:description.trim(),items:products(),createdAt:stamp(),updatedAt:stamp(),status:"active"});setLists(all);render()});
input?.addEventListener("change",async()=>{const file=input.files[0];if(!file)return;const text=await file.text(),rows=text.split(/\r?\n/).slice(1).map(r=>r.split(/[;,\t]/)),x=lists().find(v=>v.id===current),found=rows.filter(r=>r[0]?.trim()),recognized=found.filter(r=>x.items.some(p=>p.name.toLocaleLowerCase("sr")===r[0].trim().toLocaleLowerCase("sr"))),invalid=recognized.filter(r=>!Number.isFinite(Number(String(r[2]??r[1]).replace(",","."))));if(confirm(`Pregled uvoza\nPronađeno: ${found.length}\nPrepoznato: ${recognized.length}\nNeprepoznato: ${found.length-recognized.length}\nNevažeće cene: ${invalid.length}\n\nUvezi važeće cene?`)){recognized.filter(r=>!invalid.includes(r)).forEach(r=>change(r[0].trim(),String(r[2]??r[1]).replace(",","."),false));open(current)}input.value=""});
migrate();window.renderPriceLists=render;
})();