(()=>{"use strict";
 const KEY="porudzbine-price-lists-v1",HKEY="porudzbine-price-history-v1",$=id=>document.getElementById(id),home=$("priceListsHome"),detail=$("priceListDetail"),root=$("priceLists"),input=$("priceImportInput");let current=null;
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=v=>escapeHtml(String(v??"")),fmt=v=>new Intl.NumberFormat("sr-RS",{style:"currency",currency:"RSD"}).format(Number(v)||0),stamp=()=>new Date().toISOString(),id=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random();
 function lists(){return read(KEY,[])}function setLists(v){save(KEY,v)}function products(){return (state.products||[]).map(name=>({name,unit:"kom",price:0,updatedAt:stamp()}))}
 function render(){home.classList.remove("hidden");detail.classList.add("hidden");const all=lists();root.innerHTML=all.length?all.map(x=>`<article class="price-list-card"><div><strong>${esc(x.name)}</strong><span>${x.items.length} artikala · ${new Date(x.updatedAt).toLocaleDateString("sr-RS")}</span></div><div class="price-card-actions"><button data-open="${x.id}">Otvori</button><button data-rename="${x.id}">Izmeni naziv</button><button data-copy="${x.id}">Kopiraj</button><button class="danger-button" data-delete="${x.id}">Obriši</button></div></article>`).join(""):'<div class="statistics-empty">Još nema napravljenih cenovnika</div>';root.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>open(b.dataset.open));root.querySelectorAll("[data-rename]").forEach(b=>b.onclick=()=>rename(b.dataset.rename));root.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>copy(b.dataset.copy));root.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>remove(b.dataset.delete))}
 function mutate(fn){const all=lists(),x=all.find(v=>v.id===current);if(!x)return;fn(x);x.updatedAt=stamp();setLists(all);open(current)}
 function rename(i){const all=lists(),x=all.find(v=>v.id===i),name=prompt("Novi naziv cenovnika",x?.name||"")?.trim();if(name){x.name=name;x.updatedAt=stamp();setLists(all);render()}}function copy(i){const all=lists(),x=all.find(v=>v.id===i);all.push({...structuredClone(x),id:id(),name:x.name+" — kopija",updatedAt:stamp()});setLists(all);render()}function remove(i){if(confirm("Trajno obrisati ovaj cenovnik?")){setLists(lists().filter(x=>x.id!==i));render()}}
 function history(item){const rows=read(HKEY,[]).filter(h=>h.product===item&&h.listId===current);alert(rows.length?rows.map(h=>`${new Date(h.at).toLocaleString("sr-RS")}: ${fmt(h.oldPrice)} → ${fmt(h.newPrice)} (${h.listName})`).join("\n"):"Nema istorije promena cena")}
 function change(item,price){mutate(x=>{const p=x.items.find(v=>v.name===item),old=p.price;price=Number(price);if(!Number.isFinite(price)||price<0)return;p.price=price;p.updatedAt=stamp();const h=read(HKEY,[]);h.unshift({id:id(),listId:x.id,listName:x.name,product:p.name,oldPrice:old,newPrice:price,at:stamp()});save(HKEY,h)})}
 function group(){const x=lists().find(v=>v.id===current),mode=$("priceBulkMode").value,n=Number($("priceBulkValue").value),selected=[...detail.querySelectorAll("[data-select]:checked")].map(b=>b.dataset.select),items=x.items.filter(p=>!selected.length||selected.includes(p.name));if(!items.length)return showToast("Izaberi artikle");let calc=p=>mode==="up"?p*(1+n/100):mode==="down"?p*(1-n/100):mode==="same"?n:mode==="round1"?Math.round(p):Math.round(p/n)*n;const old=items.reduce((s,p)=>s+p.price,0),neu=items.reduce((s,p)=>s+Math.max(0,calc(p.price)),0),pct=old?(neu/old-1)*100:0;if(!confirm(`Pregled promene\nArtikala: ${items.length}\nStara ukupna vrednost: ${fmt(old)}\nNova ukupna vrednost: ${fmt(neu)}\nPromena: ${pct.toFixed(2)}%\n\nPrimeni izmene?`))return;items.forEach(p=>change(p.name,Math.max(0,calc(p.price))))}
 function exportFiles(pdf=false){const x=lists().find(v=>v.id===current),date=new Date().toISOString().slice(0,10),rows=[["Artikal","Jedinica mere","Cena"],...x.items.map(p=>[p.name,p.unit,p.price])];if(pdf)FileExport.pdf(x.name,`Datum generisanja: ${new Date().toLocaleDateString("sr-RS")}`,[{title:"Cenovnik",rows}]).then(b=>FileExport.share(b,`Cenovnik_${date}.pdf`));else FileExport.share(FileExport.xlsx({Cenovnik:rows}),`Cenovnik_${date}.xlsx`)}
 function open(i){current=i;const x=lists().find(v=>v.id===i);if(!x)return render();home.classList.add("hidden");detail.classList.remove("hidden");detail.innerHTML=`<button class="statistics-overview" id="pricesBack">‹ Svi cenovnici</button><div class="settings-section"><div class="section-title"><div><h3>${esc(x.name)}</h3><p class="muted">Poslednja izmena ${new Date(x.updatedAt).toLocaleString("sr-RS")}</p></div></div><div class="price-tools"><select id="priceBulkMode"><option value="up">Povećaj za %</option><option value="down">Smanji za %</option><option value="same">Postavi istu cenu</option><option value="round1">Zaokruži na dinar</option><option value="roundN">Zaokruži na 5/10 din.</option></select><input id="priceBulkValue" type="number" value="5" min="0" step="0.01"><button id="applyPriceBulk" class="primary">Pregled i primena</button></div><div class="price-export"><button id="priceImport">Uvoz iz Excel fajla</button><button id="priceXlsx">Izvoz u Excel</button><button id="pricePdf">Izvoz u PDF</button></div><div class="price-items">${x.items.map(p=>`<div><input type="checkbox" data-select="${esc(p.name)}"><span><strong>${esc(p.name)}</strong><small>${esc(p.unit)} · ${new Date(p.updatedAt).toLocaleDateString("sr-RS")}</small></span><input data-price="${esc(p.name)}" type="number" min="0" step="0.01" value="${p.price}"><button data-history="${esc(p.name)}">Istorija</button></div>`).join("")}</div></div>`;$("pricesBack").onclick=render;$("applyPriceBulk").onclick=group;$("priceXlsx").onclick=()=>exportFiles();$("pricePdf").onclick=()=>exportFiles(true);$("priceImport").onclick=()=>input.click();detail.querySelectorAll("[data-price]").forEach(el=>el.onchange=()=>change(el.dataset.price,el.value));detail.querySelectorAll("[data-history]").forEach(el=>el.onclick=()=>history(el.dataset.history))}
 $("newPriceListBtn")?.addEventListener("click",()=>{const name=prompt("Naziv novog cenovnika", "Standardni")?.trim();if(!name)return;const all=lists();all.push({id:id(),name,items:products(),updatedAt:stamp()});setLists(all);render()});
 input?.addEventListener("change",async()=>{const file=input.files[0];if(!file)return;const text=await file.text(),rows=text.split(/\r?\n/).slice(1).map(r=>r.split(/[;,\t]/)),x=lists().find(v=>v.id===current),found=rows.filter(r=>r[0]?.trim()),recognized=found.filter(r=>x.items.some(p=>p.name.toLocaleLowerCase("sr")===r[0].trim().toLocaleLowerCase("sr"))),invalid=recognized.filter(r=>!Number.isFinite(Number(String(r[2]).replace(",","."))));if(confirm(`Pregled uvoza\nPronađeno: ${found.length}\nPrepoznato: ${recognized.length}\nNeprepoznato: ${found.length-recognized.length}\nNevažeće cene: ${invalid.length}\n\nUvezi važeće cene?`))recognized.filter(r=>!invalid.includes(r)).forEach(r=>change(r[0].trim(),String(r[2]).replace(",",".")));input.value=""});
 window.renderPriceLists=render;
})();
