(()=>{
 const ROUTES_KEY="porudzbine-routes-v1",VISITS_KEY="porudzbine-route-visits-v23",FINISHED_KEY="porudzbine-route-finished-v23";
 const $=id=>document.getElementById(id),norm=v=>String(v||"").trim().toLocaleLowerCase("sr");
 const dateKey=(v=new Date())=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
 const load=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
 const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
 function routes(){return load(ROUTES_KEY,{})}
 function visits(){return load(VISITS_KEY,{})}
 function todayOrders(){const key=dateKey();return (state.orders||[]).filter(o=>dateKey(o.createdAt)===key)}
 function statusFor(name){const ordered=todayOrders().some(o=>norm(o.customer)===norm(name));if(ordered)return {type:"ordered",label:"Poručio",icon:"✓"};const rec=visits()[dateKey()]?.[norm(name)];if(rec)return {type:"no-order",label:rec.reason||"Bez porudžbine",icon:"–"};return {type:"pending",label:"Nije posećen",icon:"○"};}
 function openCustomer(name){const input=$("customerInput");input.value=name;selectCustomer(name);document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab==="order"));$("routeView").classList.remove("active");$("historyView").classList.remove("active");$("orderView").classList.add("active");$("saveBar").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
 function markNoOrder(name){const options=["Zatvoreno","Ne treba roba","Godišnji odmor","Drugi razlog"];
  const choice=prompt(`Razlog bez porudžbine za ${name}:\n1 - Zatvoreno\n2 - Ne treba roba\n3 - Godišnji odmor\n4 - Drugi razlog`,`2`);if(choice===null)return;
  let reason=options[Math.max(0,Math.min(3,Number(choice)-1))]||"Bez porudžbine";if(String(choice).trim()==="4"){const custom=prompt("Upiši razlog:","");if(custom===null)return;reason=custom.trim()||"Drugi razlog";}
  const all=visits(),key=dateKey();all[key]=all[key]||{};all[key][norm(name)]={customer:name,reason,at:new Date().toISOString()};save(VISITS_KEY,all);render();showToast("Kupac je označen kao obiđen");
 }
 function clearNoOrder(name){const all=visits(),key=dateKey();if(all[key])delete all[key][norm(name)];save(VISITS_KEY,all);render();}
 function finishRoute(){const list=routes()[String(new Date().getDay())]||[];const stats=list.map(statusFor);const ordered=stats.filter(s=>s.type==="ordered").length,noOrder=stats.filter(s=>s.type==="no-order").length,pending=stats.filter(s=>s.type==="pending").length,totalQty=todayOrders().reduce((sum,o)=>sum+Object.values(o.items||{}).reduce((a,n)=>a+(Number(n)||0),0),0);if(pending&&!confirm(`Ostalo je ${pending} neposećenih kupaca. Ipak završiti turu?`))return;const done=load(FINISHED_KEY,{});done[dateKey()]={finishedAt:new Date().toISOString(),ordered,noOrder,pending,totalQty};save(FINISHED_KEY,done);alert(`Dnevna tura završena\n\nObiđeno: ${ordered+noOrder} od ${list.length}\nPorudžbina: ${ordered}\nBez porudžbine: ${noOrder}\nNeposećeno: ${pending}\nUkupna količina: ${totalQty}`);render();}
 function render(){const box=$("routeCustomers"),summary=$("routeSummary"),label=$("routeDateLabel");if(!box||!summary)return;const day=String(new Date().getDay()),list=routes()[day]||[];label.textContent=new Intl.DateTimeFormat("sr-RS",{weekday:"long",dateStyle:"long"}).format(new Date());const statuses=list.map(name=>({name,status:statusFor(name)}));const ordered=statuses.filter(x=>x.status.type==="ordered").length,noOrder=statuses.filter(x=>x.status.type==="no-order").length,pending=statuses.length-ordered-noOrder;
  summary.innerHTML=`<div class="route-stats-v23"><span>Ukupno <strong>${list.length}</strong></span><span class="ordered">Poručilo <strong>${ordered}</strong></span><span class="no-order">Bez porudžbine <strong>${noOrder}</strong></span><span class="pending">Ostalo <strong>${pending}</strong></span></div>`;
  box.innerHTML="";if(!list.length){box.innerHTML='<div class="empty-state">Za današnji dan nema podešene ture. Dodaj kupce u Podešavanjima.</div>';return;}
  statuses.forEach(({name,status},index)=>{const card=document.createElement("article");card.className=`route-card-v23 ${status.type}`;card.draggable=true;card.dataset.name=name;card.innerHTML=`<button type="button" class="route-open-v23"><span class="route-index-v23">${index+1}</span><span class="route-status-v23">${status.icon}</span><span class="route-name-v23">${escapeHtml(name)}</span><span class="route-label-v23">${escapeHtml(status.label)}</span></button><div class="route-actions-v23"><button type="button" data-a="open">Otvori</button>${status.type==="pending"?'<button type="button" data-a="none">Nema porudžbine</button>':''}${status.type==="no-order"?'<button type="button" data-a="undo">Vrati na neposećeno</button>':''}</div>`;card.querySelector('[data-a="open"],.route-open-v23').onclick=()=>openCustomer(name);card.querySelector('[data-a="none"]')?.addEventListener("click",()=>markNoOrder(name));card.querySelector('[data-a="undo"]')?.addEventListener("click",()=>clearNoOrder(name));box.appendChild(card);});
  let dragged="";box.querySelectorAll(".route-card-v23").forEach(card=>{card.addEventListener("dragstart",()=>dragged=card.dataset.name);card.addEventListener("dragover",e=>e.preventDefault());card.addEventListener("drop",e=>{e.preventDefault();const target=card.dataset.name;if(!dragged||dragged===target)return;const all=routes(),arr=[...(all[day]||[])],from=arr.indexOf(dragged),to=arr.indexOf(target);arr.splice(to,0,arr.splice(from,1)[0]);all[day]=arr;save(ROUTES_KEY,all);render();showToast("Redosled ture je promenjen");});});
 }
 function addFinishButton(){const host=$("routeView")?.querySelector(".route-card");if(!host||$("finishRouteBtn"))return;const btn=document.createElement("button");btn.id="finishRouteBtn";btn.type="button";btn.className="primary finish-route-v23";btn.textContent="Završi turu";btn.onclick=finishRoute;host.appendChild(btn);}
 document.querySelectorAll('.tab[data-tab="route"]').forEach(b=>b.addEventListener("click",()=>setTimeout(()=>{addFinishButton();render()},0)));
 $("saveBtn")?.addEventListener("click",()=>setTimeout(render,80));window.addEventListener("storage",render);window.addEventListener("customers-changed",render);setTimeout(()=>{addFinishButton();render()},0);
})();