(()=>{
  const ROUTES_KEY="porudzbine-routes-v1";
  const DAYS=[{id:"1",name:"Ponedeljak"},{id:"2",name:"Utorak"},{id:"3",name:"Sreda"},{id:"4",name:"Četvrtak"},{id:"5",name:"Petak"},{id:"6",name:"Subota"},{id:"0",name:"Nedelja"}];
  const byId=id=>document.getElementById(id);
  const routeView=byId("routeView"),routeCustomers=byId("routeCustomers"),routeSummary=byId("routeSummary"),routeDateLabel=byId("routeDateLabel");
  const daySelect=byId("routeDaySelect"),customerInput=byId("routeCustomerInput"),customerList=byId("routeCustomerList"),settingsList=byId("routeSettingsList");
  const addBtn=byId("addRouteCustomerBtn"),routeSettingsBtn=byId("routeSettingsBtn");
  if(!routeView)return;
  const norm=v=>String(v||"").trim().toLocaleLowerCase("sr");
  function loadRoutes(){try{const data=JSON.parse(localStorage.getItem(ROUTES_KEY));return data&&typeof data==="object"?data:{};}catch{return {};}}
  let routes=loadRoutes();
  function saveRoutes(){localStorage.setItem(ROUTES_KEY,JSON.stringify(routes));window.dispatchEvent(new Event("routes-changed"));}
  function dateKey(value=new Date()){const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
  function customerNames(){return Object.keys(state.customers||{}).filter(Boolean);}
  function exactCustomer(value){const key=norm(value);return customerNames().find(name=>norm(name)===key)||"";}
  function migrateRouteCustomers(){let added=0,changed=false;Object.keys(routes).forEach(day=>{const clean=[];(routes[day]||[]).forEach(raw=>{const name=String(raw||"").trim();if(!name)return;let canonical=exactCustomer(name);if(!canonical){state.customers[name]={...(state.customers[name]||{})};canonical=name;added++;changed=true;}if(!clean.some(existing=>norm(existing)===norm(canonical)))clean.push(canonical);else changed=true;});if(clean.length!==(routes[day]||[]).length)changed=true;routes[day]=clean;});if(added){persist();renderCustomerList();window.dispatchEvent(new Event("customers-changed"));}if(changed)saveRoutes();return added;}
  function visitedToday(){const today=dateKey();return new Set((state.orders||[]).filter(o=>dateKey(o.createdAt)===today).map(o=>norm(o.customer)));}
  function currentDayId(){return String(new Date().getDay());}
  function dayName(id){return DAYS.find(d=>d.id===String(id))?.name||"Dan";}
  function renderCustomerOptions(){customerList.innerHTML="";customerNames().sort((a,b)=>a.localeCompare(b,"sr")).forEach(name=>{const o=document.createElement("option");o.value=name;customerList.appendChild(o);});}
  function renderSettings(){routes=loadRoutes();const id=daySelect.value||currentDayId(),list=routes[id]||[];settingsList.innerHTML="";if(!list.length){settingsList.innerHTML='<div class="empty-state">Nema dodatih kupaca za ovaj dan.</div>';return;}list.forEach((name,index)=>{const row=document.createElement("div");row.className="settings-row route-setting-row";row.innerHTML=`<span>${escapeHtml(name)}</span><button type="button" aria-label="Gore">↑</button><button type="button" aria-label="Dole">↓</button><button type="button" class="danger" aria-label="Ukloni">✕</button>`;const [up,down,del]=row.querySelectorAll("button");up.disabled=index===0;down.disabled=index===list.length-1;up.onclick=()=>move(id,index,-1);down.disabled=index===list.length-1;down.onclick=()=>move(id,index,1);del.onclick=()=>remove(id,name);settingsList.appendChild(row);});}
  function add(){const id=daySelect.value||currentDayId(),typed=customerInput.value.trim();if(!typed)return;const name=exactCustomer(typed);if(!name){showToast("Izaberi postojećeg kupca sa spiska Kupci");customerInput.focus();return;}routes=loadRoutes();routes[id]=routes[id]||[];if(routes[id].some(n=>norm(n)===norm(name))){showToast("Kupac je već u toj turi");return;}routes[id].push(name);saveRoutes();customerInput.value="";renderSettings();renderToday();showToast("Kupac je dodat u turu");}
  function move(id,index,delta){routes=loadRoutes();const list=routes[id]||[],target=index+delta;if(target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];saveRoutes();renderSettings();renderToday();}
  function remove(id,name){routes=loadRoutes();routes[id]=(routes[id]||[]).filter(n=>norm(n)!==norm(name));saveRoutes();renderSettings();renderToday();}
  function openCustomer(name){const canonical=exactCustomer(name);if(!canonical){showToast("Kupac više ne postoji u spisku Kupci");return;}const input=byId("customerInput");input.value=canonical;selectCustomer(canonical);document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab==="order"));routeView.classList.remove("active");byId("historyView").classList.remove("active");byId("orderView").classList.add("active");byId("saveBar").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
  function renderToday(){
    if(window.renderTodayRouteV23){window.renderTodayRouteV23();return;}
    routes=loadRoutes();const id=currentDayId(),list=routes[id]||[],visited=visitedToday();routeDateLabel.textContent=`${dayName(id)} · ${new Intl.DateTimeFormat("sr-RS",{dateStyle:"long"}).format(new Date())}`;routeCustomers.innerHTML="";const done=list.filter(n=>visited.has(norm(n))).length;routeSummary.innerHTML=`<strong>${done} od ${list.length}</strong> kupaca obiđeno${list.length?` · <span class="route-missed">${list.length-done} preostalo</span>`:""}`;if(!list.length){routeCustomers.innerHTML='<div class="empty-state">Za današnji dan nema podešene ture. Dodaj kupce u Podešavanjima.</div>';return;}list.forEach(name=>{const done=visited.has(norm(name));const item=document.createElement("button");item.type="button";item.className=`route-item ${done?"done":"missing"}`;item.innerHTML=`<span class="route-status">${done?"✓":"!"}</span><span class="route-name">${escapeHtml(name)}</span><span class="route-label">${done?"Obiđen":"Nije obiđen"}</span>`;item.onclick=()=>openCustomer(name);routeCustomers.appendChild(item);});
  }
  function openRouteSettings(){daySelect.value=currentDayId();renderCustomerOptions();renderSettings();byId("settingsDialog").showModal();window.openSettingsPanel?.("routes");}
  DAYS.forEach(day=>{const o=document.createElement("option");o.value=day.id;o.textContent=day.name;daySelect.appendChild(o);});
  daySelect.value=currentDayId();daySelect.addEventListener("change",renderSettings);addBtn.addEventListener("click",add);customerInput.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();add();}});routeSettingsBtn.addEventListener("click",openRouteSettings);byId("settingsBtn").addEventListener("click",()=>{renderCustomerOptions();renderSettings();});byId("saveBtn").addEventListener("click",()=>setTimeout(()=>{renderCustomerOptions();renderToday();},0));
  window.addEventListener("customers-changed",()=>{routes=loadRoutes();renderCustomerOptions();renderSettings();renderToday();});
  document.querySelectorAll('.tab[data-tab="route"]').forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b===btn));byId("orderView").classList.remove("active");byId("historyView").classList.remove("active");routeView.classList.add("active");byId("saveBar").classList.add("hidden");renderToday();}));
  document.querySelectorAll('.tab[data-tab="order"],.tab[data-tab="history"]').forEach(btn=>btn.addEventListener("click",()=>routeView.classList.remove("active")));
  const migrated=migrateRouteCustomers();renderCustomerOptions();renderSettings();renderToday();if(migrated)setTimeout(()=>showToast(`${migrated} kupaca iz tura dodato je u spisak Kupci`),300);
})();