(()=>{"use strict";
 const period=document.getElementById("statisticsPeriod"),label=document.getElementById("statisticsPeriodLabel"),content=document.getElementById("statisticsContent");if(!period||!content)return;
 const e=v=>escapeHtml(String(v??"")),nf=v=>new Intl.NumberFormat("sr-RS",{maximumFractionDigits:2}).format(Number(v)||0),df=v=>v?new Intl.DateTimeFormat("sr-RS",{dateStyle:"medium"}).format(new Date(v)):"—",norm=v=>String(v||"").trim().toLocaleLowerCase("sr"),total=o=>Object.values(o.items||{}).reduce((s,q)=>s+(Number(q)||0),0);
 function bounds(value=period.value,previous=false){
  const now=new Date(),start=new Date(now),end=new Date(now);end.setHours(23,59,59,999);
  switch(value){
   case "all":return[null,null];
   case "today":start.setHours(0,0,0,0);break;
   case "7days":start.setDate(start.getDate()-6);start.setHours(0,0,0,0);break;
   case "month":start.setDate(1);start.setHours(0,0,0,0);break;
   case "previousMonth":start.setMonth(start.getMonth()-1,1);start.setHours(0,0,0,0);end.setDate(0);end.setHours(23,59,59,999);break;
   case "3months":start.setMonth(start.getMonth()-2,1);start.setHours(0,0,0,0);break;
   case "year":start.setMonth(0,1);start.setHours(0,0,0,0);break;
   default:return[null,null];
  }
  if(previous){const duration=end-start+1,end2=new Date(start-1),start2=new Date(+end2-duration+1);return[start2,end2]}
  return[start,end]
 }
 function savedOrders(){return typeof window.getSavedOrders==="function"?window.getSavedOrders():[]}
 function orders(previous=false){if(previous&&period.value==="all")return[];const[s,en]=bounds(period.value,previous);return savedOrders().filter(o=>{const time=Date.parse(o.createdAt);return Number.isFinite(time)&&(!s||time>=s.getTime())&&(!en||time<=en.getTime())}).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))}
 function products(list){const m=new Map();list.forEach(o=>Object.entries(o.items||{}).forEach(([name,v])=>{const q=Number(v)||0;if(q<=0)return;const k=norm(name),r=m.get(k)||{name,quantity:0,orders:0,customers:new Set(),last:null};r.quantity+=q;r.orders++;r.customers.add(norm(o.customer));if(!r.last||new Date(o.createdAt)>new Date(r.last))r.last=o.createdAt;m.set(k,r)}));return[...m.values()].sort((a,b)=>b.quantity-a.quantity)}
 function customers(list){const m=new Map();list.forEach(o=>{const k=norm(o.customer),r=m.get(k)||{name:o.customer,orders:0,quantity:0,first:o.createdAt,last:o.createdAt};r.orders++;r.quantity+=total(o);if(new Date(o.createdAt)<new Date(r.first))r.first=o.createdAt;if(new Date(o.createdAt)>new Date(r.last))r.last=o.createdAt;m.set(k,r)});return[...m.values()].sort((a,b)=>b.quantity-a.quantity)}
 function monthly(list,product){const m=new Map();list.forEach(o=>{const key=new Date(o.createdAt).toLocaleDateString("sr-RS",{year:"numeric",month:"short"}),q=product?(Number(Object.entries(o.items||{}).find(([n])=>norm(n)===norm(product))?.[1])||0):total(o);m.set(key,(m.get(key)||0)+q)});return[...m.entries()].reverse()}
 const metric=(t,v)=>`<article class="stat-metric"><span>${e(t)}</span><strong>${typeof v==="number"?nf(v):e(v)}</strong></article>`,chart=rows=>`<div class="stat-chart">${rows.map(([n,v])=>`<div><span>${e(n)}</span><i style="--bar:${Math.max(4,100*v/Math.max(...rows.map(r=>r[1]),1))}%"></i><b>${nf(v)}</b></div>`).join("")}</div>`;
 function compare(now,prev){const d=prev?(now/prev-1)*100:now?100:0;return`${d>=0?"+":""}${nf(d)}% u odnosu na prethodni period`}
 function reports(p,c,list){const date=new Date(),slug=date.toISOString().slice(0,7),overview=[["Period izveštaja",label.textContent],["Datum generisanja",date.toLocaleDateString("sr-RS")],["Ukupan broj porudžbina",list.length],["Ukupan broj kupaca",c.length],["Ukupna količina",list.reduce((s,o)=>s+total(o),0)],["Broj različitih artikala",p.length]],pr=[["Redni broj","Naziv artikla","Ukupna količina","Broj porudžbina","Broj kupaca","Prosek po porudžbini"],...p.map((x,i)=>[i+1,x.name,x.quantity,x.orders,x.customers.size,x.quantity/x.orders])],cu=[["Redni broj","Naziv kupca","Broj porudžbina","Ukupna količina","Poslednja porudžbina"],...c.map((x,i)=>[i+1,x.name,x.orders,x.quantity,df(x.last)])];const sheets={Pregled:[["Opšti pregled","Vrednost"],...overview],Artikli:pr,Kupci:cu},sections=[{title:"Opšti pregled",rows:[["Stavka","Vrednost"],...overview]},{title:"Pregled količina artikala",rows:pr},{title:"Najbolji kupci",rows:cu}];return`<section class="statistics-block stat-reports"><h3>IZVEŠTAJI</h3><p>Izveštaj koristi izabrani period i ne sadrži naziv ni logotip firme.</p><div><button id="statPdf" class="primary">Izvezi PDF</button><button id="statXlsx" class="secondary">Izvezi Excel</button><button id="statShare" class="secondary">Podeli izveštaj</button></div></section><span hidden data-report></span>`+`<script type="application/json" id="reportSlug">${slug}</script>`}
 function bindReports(p,c,list){const slug=new Date().toISOString().slice(0,7),overview=[["Period izveštaja",label.textContent],["Datum generisanja",new Date().toLocaleDateString("sr-RS")],["Ukupan broj porudžbina",list.length],["Ukupan broj kupaca",c.length],["Ukupna količina",list.reduce((s,o)=>s+total(o),0)],["Broj različitih artikala",p.length]],pr=[["#","Artikal","Količina","Porudžbine","Kupci","Prosek"],...p.map((x,i)=>[i+1,x.name,x.quantity,x.orders,x.customers.size,x.quantity/x.orders])],cu=[["#","Kupac","Porudžbine","Količina","Poslednja"],...c.map((x,i)=>[i+1,x.name,x.orders,x.quantity,df(x.last)])],pdf=()=>FileExport.pdf("Statistika",`Period: ${label.textContent} · Generisano: ${new Date().toLocaleString("sr-RS")}`,[{title:"Opšti pregled",rows:[["Stavka","Vrednost"],...overview]},{title:"Pregled količina artikala",rows:pr},{title:"Najbolji kupci",rows:cu}]);document.getElementById("statXlsx").onclick=()=>FileExport.share(FileExport.xlsx({Pregled:[["Stavka","Vrednost"],...overview],Artikli:pr,Kupci:cu}),`Statistika_${slug}.xlsx`);document.getElementById("statPdf").onclick=async()=>FileExport.share(await pdf(),`Statistika_${slug}.pdf`);document.getElementById("statShare").onclick=async()=>FileExport.share(await pdf(),`Statistika_${slug}.pdf`)}
 function overview(){label.textContent=period.options[period.selectedIndex].text;const list=orders();if(!list.length){content.innerHTML='<div class="statistics-empty">Nema podataka za izabrani period</div>';return}const ps=products(list),cs=customers(list),qty=list.reduce((s,o)=>s+total(o),0),lines=list.reduce((s,o)=>s+Object.values(o.items||{}).filter(q=>Number(q)>0).length,0),prev=orders(true),prevP=products(prev),now=Date.now(),all=savedOrders(),lastP=new Map(),lastC=new Map();all.forEach(o=>{lastC.set(norm(o.customer),Math.max(lastC.get(norm(o.customer))||0,+new Date(o.createdAt)));Object.entries(o.items||{}).forEach(([n,q])=>{if(Number(q)>0)lastP.set(norm(n),Math.max(lastP.get(norm(n))||0,+new Date(o.createdAt)))})});const stale=(map,names)=>[30,60,90].map(d=>[`${d} dana`,names.filter(n=>now-(map.get(norm(n))||0)>=d*864e5).length]);const growth=ps.map(p=>{const old=prevP.find(x=>norm(x.name)===norm(p.name))?.quantity||0;return{name:p.name,d:p.quantity-old}}).sort((a,b)=>b.d-a.d);
 content.innerHTML=`<section class="statistics-block"><h3>OPŠTI PREGLED</h3><div class="stat-grid">${metric("Ukupan broj porudžbina",list.length)}${metric("Kupaca koji su poručivali",cs.length)}${metric("Različitih artikala",ps.length)}${metric("Ukupna količina",qty)}${metric("Prosečna količina po porudžbini",qty/list.length)}${metric("Prosečan broj različitih artikala",lines/list.length)}</div></section><section class="statistics-block"><h3>NAJPRODAVANIJI ARTIKLI</h3><div class="stat-list">${ps.slice(0,10).map((p,i)=>`<button data-product="${e(p.name)}"><b>${i+1}</b><span><strong>${e(p.name)}</strong><small>${p.orders} porudžbina · prosek ${nf(p.quantity/p.orders)}</small></span><em>${nf(p.quantity)}</em><b>›</b></button>`).join("")}</div></section><section class="statistics-block"><h3>NAJBOLJI KUPCI</h3><div class="stat-list">${cs.slice(0,10).map(c=>`<button data-customer="${e(c.name)}"><span><strong>${e(c.name)}</strong><small>${c.orders} porudžbina · ${df(c.last)}</small></span><em>${nf(c.quantity)}</em><b>›</b></button>`).join("")}</div></section><section class="statistics-block"><h3>DODATNE STATISTIKE</h3><div class="stat-grid">${metric("Novi kupci u periodu",cs.filter(c=>!savedOrders().some(o=>norm(o.customer)===norm(c.name)&&new Date(o.createdAt)<bounds()[0])).length)}${metric("Najveći rast",growth[0]?`${growth[0].name} (+${nf(growth[0].d)})`:"—")}${metric("Najveći pad",growth.at(-1)&&growth.at(-1).d<0?`${growth.at(-1).name} (${nf(growth.at(-1).d)})`:"—")}${metric("Poređenje količine",compare(qty,prev.reduce((s,o)=>s+total(o),0)))}</div><h4>Artikli koji nisu poručeni</h4>${chart(stale(lastP,[...(state.products||[])]))}<h4>Kupci koji nisu poručivali</h4>${chart(stale(lastC,Object.keys(state.customers||{})))}<h4>Ukupna količina po mesecima</h4>${chart(monthly(list))}</section>${reports(ps,cs,list)}`;content.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>productDetail(b.dataset.product));content.querySelectorAll("[data-customer]").forEach(b=>b.onclick=()=>customerDetail(b.dataset.customer));bindReports(ps,cs,list)}
 const back=t=>`<button class="statistics-overview">‹ Pregled statistike</button><div class="statistics-detail-title"><span>${e(label.textContent)}</span><h3>${e(t)}</h3></div>`;
 function productDetail(name){const list=orders().filter(o=>Number(Object.entries(o.items||{}).find(([n])=>norm(n)===norm(name))?.[1])>0),qty=list.reduce((s,o)=>s+(Number(Object.entries(o.items||{}).find(([n])=>norm(n)===norm(name))?.[1])||0),0),cs=new Map();list.forEach(o=>{const k=norm(o.customer),r=cs.get(k)||{name:o.customer,q:0,n:0};r.q+=Number(Object.entries(o.items||{}).find(([n])=>norm(n)===norm(name))?.[1])||0;r.n++;cs.set(k,r)});const prev=products(orders(true)).find(p=>norm(p.name)===norm(name))?.quantity||0;content.innerHTML=`${back(name)}<div class="stat-grid">${metric("Ukupno prodato",qty)}${metric("Broj porudžbina",list.length)}${metric("Različitih kupaca",cs.size)}${metric("Prosek po porudžbini",qty/list.length)}${metric("Poslednja prodaja",df(list[0]?.createdAt))}${metric("Prethodni period",compare(qty,prev))}</div><section class="statistics-block"><h3>KUPCI KOJI GA NAJVIŠE PORUČUJU</h3><div class="stat-simple-list">${[...cs.values()].sort((a,b)=>b.q-a.q).map(c=>`<div><strong>${e(c.name)}</strong><span>${nf(c.q)}</span></div>`).join("")}</div><h3>KOLIČINA PO MESECIMA</h3>${chart(monthly(list,name))}</section>`;content.querySelector(".statistics-overview").onclick=overview}
 function customerDetail(name){const list=orders().filter(o=>norm(o.customer)===norm(name)),qty=list.reduce((s,o)=>s+total(o),0),ps=products(list),all=savedOrders().filter(o=>norm(o.customer)===norm(name)),last=new Map();all.forEach(o=>Object.entries(o.items||{}).forEach(([n,q])=>{if(Number(q)>0)last.set(n,Math.max(last.get(n)||0,+new Date(o.createdAt))) }));const prev=orders(true).filter(o=>norm(o.customer)===norm(name)).reduce((s,o)=>s+total(o),0);content.innerHTML=`${back(name)}<div class="stat-grid">${metric("Ukupno porudžbina",list.length)}${metric("Ukupna količina",qty)}${metric("Prosek po porudžbini",qty/list.length)}${metric("Prva porudžbina",df(all.at(-1)?.createdAt))}${metric("Poslednja porudžbina",df(all[0]?.createdAt))}${metric("Prethodni period",compare(qty,prev))}</div><section class="statistics-block"><h3>NAJČEŠĆE PORUČIVANI ARTIKLI</h3><div class="stat-simple-list">${ps.slice(0,10).map(p=>`<div><strong>${e(p.name)}</strong><span>${nf(p.quantity)}</span></div>`).join("")}</div><h3>ARTIKLI KOJE DUGO NIJE PORUČIO</h3><div class="stat-simple-list">${[...last].sort((a,b)=>a[1]-b[1]).slice(0,10).map(([n,d])=>`<div><strong>${e(n)}</strong><span>${df(d)}</span></div>`).join("")||"Nema podataka."}</div><h3>KOLIČINA PO MESECIMA</h3>${chart(monthly(list))}<h3>ISTORIJA PORUDŽBINA</h3><div class="stat-history">${list.map(o=>`<article><strong>${df(o.createdAt)}</strong><span>${nf(total(o))}</span><p>${Object.entries(o.items||{}).filter(([,q])=>Number(q)>0).map(([n,q])=>`${e(n)}: ${nf(q)}`).join(" · ")}</p></article>`).join("")}</div></section>`;content.querySelector(".statistics-overview").onclick=overview}
 window.renderStatistics=overview;period.addEventListener("change",overview);
})();
