(()=>{
 "use strict";
 const DRAFT_KEY="trebovanje-draft-v24",ROUTES_KEY="porudzbine-routes-v1",VISITS_KEY="porudzbine-route-visits-v23";
 const $=id=>document.getElementById(id),norm=v=>String(v||"").trim().toLocaleLowerCase("sr");
 const dateKey=(v=new Date())=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
 const readJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
 const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 function injectStyle(){if($("v24-style"))return;const s=document.createElement("style");s.id="v24-style";s.textContent=`
 .v24-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.v24-actions button{flex:1 1 180px}
 .v24-route-meta{grid-column:3/5;font-size:12px;color:#66737d;line-height:1.35;margin-top:2px}.v24-note{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}
 .v24-customer-dialog{border:0;border-radius:18px;padding:0;width:min(640px,calc(100% - 20px));max-height:88vh}.v24-customer-dialog::backdrop{background:rgba(18,31,37,.52)}.v24-customer-body{padding:16px;max-height:85vh;overflow:auto}.v24-customer-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v24-customer-head h2{margin:0}.v24-history{display:grid;gap:8px;margin-top:14px}.v24-history article{border:1px solid #dce3e7;border-radius:12px;padding:10px}.v24-avg{padding:10px;background:#f3f7f7;border-radius:12px;margin-top:12px;line-height:1.5}.v24-report-btn{margin-top:8px;width:100%}
 `;document.head.appendChild(s)}
 function switchToRoute(){const tab=document.querySelector('.tab[data-tab="route"]');if(tab){tab.click();setTimeout(()=>window.scrollTo({top:0}),0)}}
 function customerOrders(name){return (state.orders||[]).filter(o=>norm(o.customer)===norm(name)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
 function addCustomerButtons(){const card=document.querySelector(".customer-card");if(!card||$("v24CustomerActions"))return;const wrap=document.createElement("div");wrap.id="v24CustomerActions";wrap.className="v24-actions";wrap.innerHTML='<button id="repeatLastBtn" type="button" class="secondary">Ponovi prethodno trebovanje</button><button id="customerCardBtn" type="button" class="secondary">Kartica kupca</button>';card.appendChild(wrap);
 $("repeatLastBtn").onclick=()=>{const name=$("customerInput").value.trim(),last=customerOrders(name)[0];if(!name){showToast("Prvo izaberi kupca");return}if(!last){showToast("Kupac nema prethodno trebovanje");return}document.querySelectorAll(".qty").forEach(i=>i.value=Number(last.items?.[i.dataset.product]||0)||"");updateDraftStatus();saveDraft();showToast("Prethodno trebovanje je učitano")};
 $("customerCardBtn").onclick=showCustomerCard;
 }
 function showCustomerCard(){const name=$("customerInput").value.trim();if(!name){showToast("Prvo izaberi kupca");return}const orders=customerOrders(name).slice(0,10);const totals={},counts={};orders.forEach(o=>Object.entries(o.items||{}).forEach(([p,q])=>{q=Number(q)||0;if(q>0){totals[p]=(totals[p]||0)+q;counts[p]=(counts[p]||0)+1}}));const avg=Object.keys(totals).sort((a,b)=>totals[b]-totals[a]).slice(0,12).map(p=>`${esc(p)}: <strong>${(totals[p]/counts[p]).toFixed(1)}</strong>`).join(" · ")||"Nema podataka";let dlg=$("v24CustomerDialog");if(!dlg){dlg=document.createElement("dialog");dlg.id="v24CustomerDialog";dlg.className="v24-customer-dialog";document.body.appendChild(dlg)}const note=state.customers?.[name]?.note||"";dlg.innerHTML=`<div class="v24-customer-body"><div class="v24-customer-head"><div><h2>${esc(name)}</h2><p class="muted">Poslednjih ${orders.length} trebovanja</p></div><button class="icon-button" type="button">✕</button></div>${note?`<div class="history-note">${esc(note)}</div>`:""}<div class="v24-avg"><strong>Prosečne količine:</strong><br>${avg}</div><div class="v24-history">${orders.map(o=>`<article><strong>${new Intl.DateTimeFormat("sr-RS",{dateStyle:"short",timeStyle:"short"}).format(new Date(o.createdAt))}</strong><div>${Object.entries(o.items||{}).filter(([,q])=>Number(q)>0).map(([p,q])=>`${esc(p)}: ${q}`).join(" · ")||"Bez stavki"}</div>${o.note?`<div class="history-note">${esc(o.note)}</div>`:""}</article>`).join("")||'<div class="empty-state">Nema prethodnih trebovanja.</div>'}</div></div>`;dlg.querySelector("button").onclick=()=>dlg.close();dlg.showModal()}
 function saveDraft(){const name=$("customerInput")?.value.trim();const items={};document.querySelectorAll(".qty").forEach(i=>{if(i.value)items[i.dataset.product]=i.value});const note=$("orderNote")?.value||"";if(!name&&!Object.keys(items).length&&!note){localStorage.removeItem(DRAFT_KEY);return}localStorage.setItem(DRAFT_KEY,JSON.stringify({name,items,note,customerNote:$("customerNote")?.value||"",savedAt:new Date().toISOString()}))}
 function restoreDraft(){const d=readJson(DRAFT_KEY,null);if(!d||(!d.name&&!Object.keys(d.items||{}).length))return;const current=$("customerInput").value.trim();if(current)return;$("customerInput").value=d.name||"";selectCustomer(d.name||"");$("orderNote").value=d.note||"";$("customerNote").value=d.customerNote||$("customerNote").value;document.querySelectorAll(".qty").forEach(i=>i.value=d.items?.[i.dataset.product]||"");updateDraftStatus();showToast("Nedovršeno trebovanje je vraćeno")}
 function bindDraft(){["customerInput","customerNote","orderNote"].forEach(id=>$(id)?.addEventListener("input",saveDraft));$("products")?.addEventListener("input",saveDraft);$("newOrderBtn")?.addEventListener("click",()=>localStorage.removeItem(DRAFT_KEY))}
 function nextRouteCustomer(current){const routes=readJson(ROUTES_KEY,{}),list=routes[String(new Date().getDay())]||[],orders=(state.orders||[]).filter(o=>dateKey(o.createdAt)===dateKey()),visits=readJson(VISITS_KEY,{})[dateKey()]||{};const done=n=>orders.some(o=>norm(o.customer)===norm(n))||visits[norm(n)];let idx=list.findIndex(n=>norm(n)===norm(current));for(let step=1;step<=list.length;step++){const n=list[(idx+step+list.length)%list.length];if(n&&!done(n))return n}return null}
 function openNextAfterSave(){const btn=$("saveBtn");if(!btn)return;btn.addEventListener("click",()=>{const before=(state.orders||[]).length,current=$("customerInput").value.trim();setTimeout(()=>{if((state.orders||[]).length<=before)return;localStorage.removeItem(DRAFT_KEY);const next=nextRouteCustomer(current);if(!next){switchToRoute();showToast("Današnja tura je završena");return}$("customerInput").value=next;selectCustomer(next);switchTab("order");window.scrollTo({top:0,behavior:"smooth"});showToast(`Sledeći kupac: ${next}`)},180)})}
 function enrichRoute(){document.querySelectorAll(".route-card-v23").forEach(card=>{if(card.querySelector(".v24-route-meta"))return;const name=card.dataset.name,last=customerOrders(name)[0],note=state.customers?.[name]?.note||"";const meta=document.createElement("div");meta.className="v24-route-meta";if(last){const count=Object.values(last.items||{}).filter(q=>Number(q)>0).length;meta.innerHTML=`Poslednje: ${new Intl.DateTimeFormat("sr-RS",{dateStyle:"short"}).format(new Date(last.createdAt))} · ${count} artikala${note?`<span class="v24-note">Napomena: ${esc(note)}</span>`:""}`;}else meta.innerHTML=`Nema prethodnog trebovanja${note?`<span class="v24-note">Napomena: ${esc(note)}</span>`:""}`;card.querySelector(".route-open-v23")?.appendChild(meta)})}
 function addDailyPdf(){const box=document.querySelector(".daily-export-box");if(!box||$("dailyPdfBtn"))return;const b=document.createElement("button");b.id="dailyPdfBtn";b.type="button";b.className="secondary v24-report-btn";b.textContent="PDF izveštaj za taj dan";b.onclick=()=>{const value=$("dailyExportDate").value||dateKey(),orders=(state.orders||[]).filter(o=>dateKey(o.createdAt)===value);if(!orders.length){showToast("Nema trebovanja za izabrani datum");return}const totals={};orders.forEach(o=>Object.entries(o.items||{}).forEach(([p,q])=>totals[p]=(totals[p]||0)+(Number(q)||0)));const win=window.open("","_blank");if(!win){showToast("Dozvoli otvaranje novog prozora");return}win.document.write(`<!doctype html><meta charset="utf-8"><title>Dnevni izveštaj ${value}</title><style>body{font-family:Arial;padding:28px}table{width:100%;border-collapse:collapse;margin:16px 0}td,th{border:1px solid #aaa;padding:8px;text-align:left}</style><h1>Dnevni izveštaj – ${value}</h1><p>Broj trebovanja: <strong>${orders.length}</strong></p><h2>Kupci</h2><table><tr><th>Kupac</th><th>Broj artikala</th><th>Ukupna količina</th></tr>${orders.map(o=>`<tr><td>${esc(o.customer)}</td><td>${Object.values(o.items||{}).filter(q=>Number(q)>0).length}</td><td>${Object.values(o.items||{}).reduce((a,q)=>a+(Number(q)||0),0)}</td></tr>`).join("")}</table><h2>Ukupno po artiklima</h2><table>${Object.entries(totals).filter(([,q])=>q>0).sort((a,b)=>b[1]-a[1]).map(([p,q])=>`<tr><td>${esc(p)}</td><td>${q}</td></tr>`).join("")}</table><script>window.onload=()=>window.print()<\/script>`);win.document.close()};box.appendChild(b)}
 function init(){injectStyle();addCustomerButtons();bindDraft();openNextAfterSave();addDailyPdf();const routeBox=$("routeCustomers");if(routeBox)new MutationObserver(enrichRoute).observe(routeBox,{childList:true,subtree:true});setTimeout(()=>{restoreDraft();switchToRoute();enrichRoute()},250)}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();