(()=>{
 "use strict";
 const DRAFT_KEY="trebovanje-draft-v24",ROUTES_KEY="porudzbine-routes-v1",VISITS_KEY="porudzbine-route-visits-v23",CATEGORY_KEY="porudzbine-product-categories-v1",RECENT_DAYS=90;
 const $=id=>document.getElementById(id),norm=v=>String(v||"").trim().toLocaleLowerCase("sr");
 const dateKey=(v=new Date())=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
 const readJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
 const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 function injectStyle(){if($("v24-style"))return;const s=document.createElement("style");s.id="v24-style";s.textContent=`
 .v24-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.v24-actions button{flex:1 1 180px}
 .v24-route-meta{grid-column:3/5;font-size:12px;color:#66737d;line-height:1.35;margin-top:2px}.v24-note{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}
 .v24-customer-dialog,.v245-product-dialog{border:0;border-radius:18px;padding:0;width:min(640px,calc(100% - 20px));max-height:88vh}.v24-customer-dialog::backdrop,.v245-product-dialog::backdrop{background:rgba(18,31,37,.52)}.v24-customer-body,.v245-product-body{padding:16px;max-height:85vh;overflow:auto}.v24-customer-head,.v245-product-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v24-customer-head h2,.v245-product-head h2{margin:0}.v24-history{display:grid;gap:8px;margin-top:14px}.v24-history article{border:1px solid #dce3e7;border-radius:12px;padding:10px}.v24-avg{padding:10px;background:#f3f7f7;border-radius:12px;margin-top:12px;line-height:1.5}.v24-report-btn{margin-top:8px;width:100%}
 .v245-product-name{min-width:0}.v245-title{display:flex;align-items:center;gap:4px;flex-wrap:wrap}.v245-name-button,.v245-star{border:0;background:transparent;padding:0;font:inherit;cursor:pointer}.v245-name-button{font-weight:800;color:inherit;text-align:left}.v245-name-button:focus-visible,.v245-star:focus-visible{outline:2px solid var(--brand);outline-offset:2px;border-radius:3px}.v245-star{font-size:17px;line-height:1;transform-origin:center;transition:transform .14s ease,filter .14s ease}.v245-star:active,.v245-star.v245-star-touched{transform:scale(1.22);filter:drop-shadow(0 0 4px rgba(255,193,7,.9))}.v245-suggest{display:block;color:#b86600;font-size:10px;font-weight:700;line-height:1.25;margin-top:3px}.v245-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:14px}.v245-stat{background:#f3f7f7;border-radius:12px;padding:10px}.v245-stat strong{display:block;font-size:18px}.v245-product-row .product-name>small{display:block}.v245-help{margin:8px 0 0;color:#66737d;font-size:12px}
 `;document.head.appendChild(s)}
 function switchToRoute(){const tab=document.querySelector('.tab[data-tab="route"]');if(tab){tab.click();setTimeout(()=>window.scrollTo({top:0}),0)}}
 function customerOrders(name){return (state.orders||[]).filter(o=>norm(o.customer)===norm(name)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
 function productStats(customer){const now=Date.now(),cutoff=now-RECENT_DAYS*86400000,stats={};state.products.forEach(p=>stats[p]={name:p,totalOrders:0,totalQty:0,recentOrders:0,recentQty:0,lastDate:null,lastQty:0});customerOrders(customer).forEach(o=>{const t=new Date(o.createdAt).getTime();Object.entries(o.items||{}).forEach(([p,value])=>{const q=Number(value)||0;if(q<=0||!stats[p])return;const x=stats[p];x.totalOrders++;x.totalQty+=q;if(t>=cutoff){x.recentOrders++;x.recentQty+=q}if(!x.lastDate||t>new Date(x.lastDate).getTime()){x.lastDate=o.createdAt;x.lastQty=q}})});Object.values(stats).forEach(x=>{x.daysSince=x.lastDate?Math.max(0,Math.floor((now-new Date(x.lastDate).getTime())/86400000)):null;x.suggest=x.totalOrders>0&&x.recentOrders===0&&x.daysSince>=RECENT_DAYS;x.average=x.totalOrders?x.totalQty/x.totalOrders:0});return stats}
 function sortedProducts(customer){const stats=productStats(customer);return [...state.products].sort((a,b)=>{const x=stats[a],y=stats[b];return y.recentOrders-x.recentOrders||y.recentQty-x.recentQty||y.totalOrders-x.totalOrders||y.totalQty-x.totalQty||state.products.indexOf(a)-state.products.indexOf(b)})}
 function showProductHistory(name){const customer=$("customerInput").value.trim();if(!customer)return;const x=productStats(customer)[name];if(!x)return;let dlg=$("v245ProductDialog");if(!dlg){dlg=document.createElement("dialog");dlg.id="v245ProductDialog";dlg.className="v245-product-dialog";document.body.appendChild(dlg)}dlg.innerHTML=`<div class="v245-product-body"><div class="v245-product-head"><div><h2>${esc(name)}${x.totalOrders?" ⭐":""}</h2><p class="muted">${esc(customer)}</p></div><button class="icon-button" type="button">✕</button></div>${x.suggest?`<div class="history-note">⚠️ Predložiti kupcu — nije poručen ${x.daysSince} dana.</div>`:""}<div class="v245-stats"><div class="v245-stat"><span>Poslednja kupovina</span><strong>${x.lastDate?new Intl.DateTimeFormat("sr-RS",{dateStyle:"short"}).format(new Date(x.lastDate)):"—"}</strong></div><div class="v245-stat"><span>Poslednja količina</span><strong>${x.lastQty||0}</strong></div><div class="v245-stat"><span>Broj trebovanja</span><strong>${x.totalOrders}</strong></div><div class="v245-stat"><span>Ukupna količina</span><strong>${x.totalQty}</strong></div><div class="v245-stat"><span>Prosek po trebovanju</span><strong>${x.average.toFixed(1)}</strong></div><div class="v245-stat"><span>U poslednja 3 meseca</span><strong>${x.recentOrders}</strong></div></div></div>`;dlg.querySelector("button").onclick=()=>dlg.close();dlg.showModal()}
 function installSmartProducts(){const baseRender=renderProducts;renderProducts=function(keepValues={}){if(!selectedCustomer){baseRender(keepValues);return}const previous=lastOrder(selectedCustomer)?.items||{},stats=productStats(selectedCustomer),categories=readJson(CATEGORY_KEY,{assignments:{}}).assignments||{};els.products.innerHTML="";els.noProducts.classList.toggle("hidden",state.products.length>0);sortedProducts(selectedCustomer).forEach(name=>{const x=stats[name],row=document.createElement("div");row.className="product-row row-grid compact-product-row v245-product-row";const star=x.totalOrders?`<button class="v245-star" type="button" aria-label="Statistika za ${esc(name)}">⭐</button>`:"",suggest=x.suggest?`<small class="v245-suggest">⚠️ Predložiti (${x.daysSince} dana)</small>`:"";row.innerHTML=`<div class="product-name v245-product-name"><span class="v245-title"><button class="v245-name-button" type="button">${esc(name)}</button>${star}</span>${suggest}<small>${esc(categories[name]||"")}</small></div><div class="previous">${Number(previous[name]||0)||"—"}</div><input class="qty" inputmode="numeric" pattern="[0-9]*" min="0" aria-label="Danas ${esc(name)}" data-product="${esc(name)}" value="${esc(keepValues[name]||"")}" />`;const nameButton=row.querySelector(".v245-name-button"),starButton=row.querySelector(".v245-star"),input=row.querySelector("input");nameButton.onclick=()=>showProductHistory(name);if(starButton){starButton.onclick=()=>showProductHistory(name);starButton.addEventListener("pointerdown",()=>{starButton.classList.remove("v245-star-touched");requestAnimationFrame(()=>starButton.classList.add("v245-star-touched"));setTimeout(()=>starButton.classList.remove("v245-star-touched"),180)})}input.addEventListener("focus",()=>input.select());input.addEventListener("input",()=>{input.value=input.value.replace(/[^0-9]/g,"");window.markOrderDirty?.();saveDraft()});input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();const inputs=[...document.querySelectorAll(".qty")],index=inputs.indexOf(input);(inputs[index+1]||els.orderNote).focus()}});els.products.appendChild(row)});const extra=$("extraProductBox");if(extra)extra.classList.add("hidden");updateDraftStatus()}}
 function addCustomerButtons(){const card=document.querySelector(".customer-card");if(!card||$("v24CustomerActions"))return;const wrap=document.createElement("div");wrap.id="v24CustomerActions";wrap.className="v24-actions";wrap.innerHTML='<button id="repeatLastBtn" type="button" class="secondary">Ponovi prethodno trebovanje</button><button id="customerCardBtn" type="button" class="secondary">Kartica kupca</button>';card.appendChild(wrap);$("repeatLastBtn").onclick=()=>{const name=$("customerInput").value.trim(),last=customerOrders(name)[0];if(!name){showToast("Prvo izaberi kupca");return}if(!last){showToast("Kupac nema prethodno trebovanje");return}document.querySelectorAll(".qty").forEach(i=>i.value=Number(last.items?.[i.dataset.product]||0)||"");updateDraftStatus();saveDraft();showToast("Prethodno trebovanje je učitano")};$("customerCardBtn").onclick=showCustomerCard}
 function showCustomerCard(){const name=$("customerInput").value.trim();if(!name){showToast("Prvo izaberi kupca");return}const orders=customerOrders(name).slice(0,10),totals={},counts={};orders.forEach(o=>Object.entries(o.items||{}).forEach(([p,q])=>{q=Number(q)||0;if(q>0){totals[p]=(totals[p]||0)+q;counts[p]=(counts[p]||0)+1}}));const avg=Object.keys(totals).sort((a,b)=>totals[b]-totals[a]).slice(0,12).map(p=>`${esc(p)}: <strong>${(totals[p]/counts[p]).toFixed(1)}</strong>`).join(" · ")||"Nema podataka";let dlg=$("v24CustomerDialog");if(!dlg){dlg=document.createElement("dialog");dlg.id="v24CustomerDialog";dlg.className="v24-customer-dialog";document.body.appendChild(dlg)}const note=state.customers?.[name]?.note||"";dlg.innerHTML=`<div class="v24-customer-body"><div class="v24-customer-head"><div><h2>${esc(name)}</h2><p class="muted">Poslednjih ${orders.length} trebovanja</p></div><button class="icon-button" type="button">✕</button></div>${note?`<div class="history-note">${esc(note)}</div>`:""}<div class="v24-avg"><strong>Prosečne količine:</strong><br>${avg}</div><div class="v24-history">${orders.map(o=>`<article><strong>${new Intl.DateTimeFormat("sr-RS",{dateStyle:"short",timeStyle:"short"}).format(new Date(o.createdAt))}</strong><div>${Object.entries(o.items||{}).filter(([,q])=>Number(q)>0).map(([p,q])=>`${esc(p)}: ${q}`).join(" · ")||"Bez stavki"}</div>${o.note?`<div class="history-note">${esc(o.note)}</div>`:""}</article>`).join("")||'<div class="empty-state">Nema prethodnih trebovanja.</div>'}</div></div>`;dlg.querySelector("button").onclick=()=>dlg.close();dlg.showModal()}
 let draftTimer=0;function writeDraft(){const name=$("customerInput")?.value.trim(),items={};document.querySelectorAll(".qty").forEach(i=>{if(i.value)items[i.dataset.product]=i.value});const note=$("orderNote")?.value||"";if(!name&&!Object.keys(items).length&&!note){localStorage.removeItem(DRAFT_KEY);return}localStorage.setItem(DRAFT_KEY,JSON.stringify({name,items,note,customerNote:$("customerNote")?.value||"",savedAt:new Date().toISOString()}))}
 function restoreDraft(){const d=readJson(DRAFT_KEY,null);if(!d||(!d.name&&!Object.keys(d.items||{}).length))return;const current=$("customerInput").value.trim();if(current)return;$("customerInput").value=d.name||"";selectCustomer(d.name||"");$("orderNote").value=d.note||"";$("customerNote").value=d.customerNote||$("customerNote").value;document.querySelectorAll(".qty").forEach(i=>i.value=d.items?.[i.dataset.product]||"");updateDraftStatus();showToast("Nedovršeno trebovanje je vraćeno")}
 function saveDraft(){clearTimeout(draftTimer);draftTimer=setTimeout(writeDraft,180)}
 function bindDraft(){["customerInput","customerNote","orderNote"].forEach(id=>$(id)?.addEventListener("input",saveDraft));$("products")?.addEventListener("input",saveDraft);$("newOrderBtn")?.addEventListener("click",()=>localStorage.removeItem(DRAFT_KEY))}
 function nextRouteCustomer(current){const routes=readJson(ROUTES_KEY,{}),list=routes[String(new Date().getDay())]||[],orders=(state.orders||[]).filter(o=>dateKey(o.createdAt)===dateKey()),visits=readJson(VISITS_KEY,{})[dateKey()]||{},done=n=>orders.some(o=>norm(o.customer)===norm(n))||visits[norm(n)];let idx=list.findIndex(n=>norm(n)===norm(current));for(let step=1;step<=list.length;step++){const n=list[(idx+step+list.length)%list.length];if(n&&!done(n))return n}return null}
 function openNextAfterSave(){const btn=$("saveBtn");if(!btn)return;btn.addEventListener("click",()=>{const before=(state.orders||[]).length,current=$("customerInput").value.trim();setTimeout(()=>{if((state.orders||[]).length<=before)return;localStorage.removeItem(DRAFT_KEY);const next=nextRouteCustomer(current);if(!next){switchToRoute();showToast("Današnja tura je završena");return}$("customerInput").value=next;selectCustomer(next);switchTab("order");window.scrollTo({top:0,behavior:"smooth"});showToast(`Sledeći kupac: ${next}`)},180)})}
 function enrichRoute(){document.querySelectorAll(".route-card-v23").forEach(card=>{if(card.querySelector(".v24-route-meta"))return;const name=card.dataset.name,last=customerOrders(name)[0],note=state.customers?.[name]?.note||"",meta=document.createElement("div");meta.className="v24-route-meta";if(last){const count=Object.values(last.items||{}).filter(q=>Number(q)>0).length;meta.innerHTML=`Poslednje: ${new Intl.DateTimeFormat("sr-RS",{dateStyle:"short"}).format(new Date(last.createdAt))} · ${count} artikala${note?`<span class="v24-note">Napomena: ${esc(note)}</span>`:""}`}else meta.innerHTML=`Nema prethodnog trebovanja${note?`<span class="v24-note">Napomena: ${esc(note)}</span>`:""}`;card.querySelector(".route-open-v23")?.appendChild(meta)})}
 function addDailyPdf(){const box=document.querySelector(".daily-export-box");if(!box||$("dailyPdfBtn"))return;const b=document.createElement("button");b.id="dailyPdfBtn";b.type="button";b.className="secondary v24-report-btn";b.textContent="PDF izveštaj za taj dan";b.onclick=()=>{const value=$("dailyExportDate").value||dateKey(),orders=(state.orders||[]).filter(o=>dateKey(o.createdAt)===value);if(!orders.length){showToast("Nema trebovanja za izabrani datum");return}const totals={};orders.forEach(o=>Object.entries(o.items||{}).forEach(([p,q])=>totals[p]=(totals[p]||0)+(Number(q)||0)));const win=window.open("","_blank");if(!win){showToast("Dozvoli otvaranje novog prozora");return}win.document.write(`<!doctype html><meta charset="utf-8"><title>Dnevni izveštaj ${value}</title><style>body{font-family:Arial;padding:28px}table{width:100%;border-collapse:collapse;margin:16px 0}td,th{border:1px solid #aaa;padding:8px;text-align:left}</style><h1>Dnevni izveštaj – ${value}</h1><p>Broj trebovanja: <strong>${orders.length}</strong></p><h2>Kupci</h2><table><tr><th>Kupac</th><th>Broj artikala</th><th>Ukupna količina</th></tr>${orders.map(o=>`<tr><td>${esc(o.customer)}</td><td>${Object.values(o.items||{}).filter(q=>Number(q)>0).length}</td><td>${Object.values(o.items||{}).reduce((a,q)=>a+(Number(q)||0),0)}</td></tr>`).join("")}</table><h2>Ukupno po artiklima</h2><table>${Object.entries(totals).filter(([,q])=>q>0).sort((a,b)=>b[1]-a[1]).map(([p,q])=>`<tr><td>${esc(p)}</td><td>${q}</td></tr>`).join("")}</table><script>window.onload=()=>window.print()<\/script>`);win.document.close()};box.appendChild(b)}
 function init(){injectStyle();installSmartProducts();addCustomerButtons();bindDraft();openNextAfterSave();addDailyPdf();const routeBox=$("routeCustomers");if(routeBox)new MutationObserver(enrichRoute).observe(routeBox,{childList:true,subtree:true});setTimeout(()=>{restoreDraft();switchToRoute();enrichRoute()},250)}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
